// HT66F2390.h
//	This file contains the definition of registers for
//		Holtek HT66F2390 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.7, 4
// Do not modify manually.

#ifndef _HT66F2390_H_
#define _HT66F2390_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __pbp0 : 1;
	unsigned char __pbp1 : 1;
	unsigned char __pbp2 : 1;
	unsigned char : 5;
} __pbp_bits;

typedef union {
	__pbp_bits bits;
	__sfr_byte byte;
} __pbp_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char __lrf : 1;
	unsigned char __lvrf : 1;
	unsigned char __rstf : 1;
	unsigned char : 4;
} __rstfc_bits;

typedef union {
	__rstfc_bits bits;
	__sfr_byte byte;
} __rstfc_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __int0e : 1;
	unsigned char __int1e : 1;
	unsigned char __cp0e : 1;
	unsigned char __int0f : 1;
	unsigned char __int1f : 1;
	unsigned char __cp0f : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __cp1e : 1;
	unsigned char __mf0e : 1;
	unsigned char __mf1e : 1;
	unsigned char __ade : 1;
	unsigned char __cp1f : 1;
	unsigned char __mf0f : 1;
	unsigned char __mf1f : 1;
	unsigned char __adf : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __mf2e : 1;
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __mf3e : 1;
	unsigned char __mf2f : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __mf3f : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __int2e : 1;
	unsigned char __int3e : 1;
	unsigned char __mf4e : 1;
	unsigned char __mf5e : 1;
	unsigned char __int2f : 1;
	unsigned char __int3f : 1;
	unsigned char __mf4f : 1;
	unsigned char __mf5f : 1;
} __intc3_bits;

typedef union {
	__intc3_bits bits;
	__sfr_byte byte;
} __intc3_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char __pb4 : 1;
	unsigned char __pb5 : 1;
	unsigned char __pb6 : 1;
	unsigned char __pb7 : 1;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char __pbc4 : 1;
	unsigned char __pbc5 : 1;
	unsigned char __pbc6 : 1;
	unsigned char __pbc7 : 1;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char __pbpu4 : 1;
	unsigned char __pbpu5 : 1;
	unsigned char __pbpu6 : 1;
	unsigned char __pbpu7 : 1;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char __pc6 : 1;
	unsigned char __pc7 : 1;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char __pcc6 : 1;
	unsigned char __pcc7 : 1;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char __pcpu6 : 1;
	unsigned char __pcpu7 : 1;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char __pd3 : 1;
	unsigned char __pd4 : 1;
	unsigned char __pd5 : 1;
	unsigned char __pd6 : 1;
	unsigned char : 1;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char __pdc3 : 1;
	unsigned char __pdc4 : 1;
	unsigned char __pdc5 : 1;
	unsigned char __pdc6 : 1;
	unsigned char : 1;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char __pdpu3 : 1;
	unsigned char __pdpu4 : 1;
	unsigned char __pdpu5 : 1;
	unsigned char __pdpu6 : 1;
	unsigned char : 1;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char __pe0 : 1;
	unsigned char __pe1 : 1;
	unsigned char __pe2 : 1;
	unsigned char __pe3 : 1;
	unsigned char __pe4 : 1;
	unsigned char : 3;
} __pe_bits;

typedef union {
	__pe_bits bits;
	__sfr_byte byte;
} __pe_type;

typedef struct {
	unsigned char __pec0 : 1;
	unsigned char __pec1 : 1;
	unsigned char __pec2 : 1;
	unsigned char __pec3 : 1;
	unsigned char __pec4 : 1;
	unsigned char : 3;
} __pec_bits;

typedef union {
	__pec_bits bits;
	__sfr_byte byte;
} __pec_type;

typedef struct {
	unsigned char __pepu0 : 1;
	unsigned char __pepu1 : 1;
	unsigned char __pepu2 : 1;
	unsigned char __pepu3 : 1;
	unsigned char __pepu4 : 1;
	unsigned char : 3;
} __pepu_bits;

typedef union {
	__pepu_bits bits;
	__sfr_byte byte;
} __pepu_type;

typedef struct {
	unsigned char __pf0 : 1;
	unsigned char __pf1 : 1;
	unsigned char __pf2 : 1;
	unsigned char __pf3 : 1;
	unsigned char __pf4 : 1;
	unsigned char __pf5 : 1;
	unsigned char __pf6 : 1;
	unsigned char __pf7 : 1;
} __pf_bits;

typedef union {
	__pf_bits bits;
	__sfr_byte byte;
} __pf_type;

typedef struct {
	unsigned char __pfc0 : 1;
	unsigned char __pfc1 : 1;
	unsigned char __pfc2 : 1;
	unsigned char __pfc3 : 1;
	unsigned char __pfc4 : 1;
	unsigned char __pfc5 : 1;
	unsigned char __pfc6 : 1;
	unsigned char __pfc7 : 1;
} __pfc_bits;

typedef union {
	__pfc_bits bits;
	__sfr_byte byte;
} __pfc_type;

typedef struct {
	unsigned char __pfpu0 : 1;
	unsigned char __pfpu1 : 1;
	unsigned char __pfpu2 : 1;
	unsigned char __pfpu3 : 1;
	unsigned char __pfpu4 : 1;
	unsigned char __pfpu5 : 1;
	unsigned char __pfpu6 : 1;
	unsigned char __pfpu7 : 1;
} __pfpu_bits;

typedef union {
	__pfpu_bits bits;
	__sfr_byte byte;
} __pfpu_type;

typedef struct {
	unsigned char __pg0 : 1;
	unsigned char __pg1 : 1;
	unsigned char __pg2 : 1;
	unsigned char __pg3 : 1;
	unsigned char __pg4 : 1;
	unsigned char __pg5 : 1;
	unsigned char __pg6 : 1;
	unsigned char __pg7 : 1;
} __pg_bits;

typedef union {
	__pg_bits bits;
	__sfr_byte byte;
} __pg_type;

typedef struct {
	unsigned char __pgc0 : 1;
	unsigned char __pgc1 : 1;
	unsigned char __pgc2 : 1;
	unsigned char __pgc3 : 1;
	unsigned char __pgc4 : 1;
	unsigned char __pgc5 : 1;
	unsigned char __pgc6 : 1;
	unsigned char __pgc7 : 1;
} __pgc_bits;

typedef union {
	__pgc_bits bits;
	__sfr_byte byte;
} __pgc_type;

typedef struct {
	unsigned char __pgpu0 : 1;
	unsigned char __pgpu1 : 1;
	unsigned char __pgpu2 : 1;
	unsigned char __pgpu3 : 1;
	unsigned char __pgpu4 : 1;
	unsigned char __pgpu5 : 1;
	unsigned char __pgpu6 : 1;
	unsigned char __pgpu7 : 1;
} __pgpu_bits;

typedef union {
	__pgpu_bits bits;
	__sfr_byte byte;
} __pgpu_type;

typedef struct {
	unsigned char __ph0 : 1;
	unsigned char __ph1 : 1;
	unsigned char __ph2 : 1;
	unsigned char __ph3 : 1;
	unsigned char __ph4 : 1;
	unsigned char __ph5 : 1;
	unsigned char : 2;
} __ph_bits;

typedef union {
	__ph_bits bits;
	__sfr_byte byte;
} __ph_type;

typedef struct {
	unsigned char __phc0 : 1;
	unsigned char __phc1 : 1;
	unsigned char __phc2 : 1;
	unsigned char __phc3 : 1;
	unsigned char __phc4 : 1;
	unsigned char __phc5 : 1;
	unsigned char : 2;
} __phc_bits;

typedef union {
	__phc_bits bits;
	__sfr_byte byte;
} __phc_type;

typedef struct {
	unsigned char __phpu0 : 1;
	unsigned char __phpu1 : 1;
	unsigned char __phpu2 : 1;
	unsigned char __phpu3 : 1;
	unsigned char __phpu4 : 1;
	unsigned char __phpu5 : 1;
	unsigned char : 2;
} __phpu_bits;

typedef union {
	__phpu_bits bits;
	__sfr_byte byte;
} __phpu_type;

typedef struct {
	unsigned char __pmps0 : 1;
	unsigned char __pmps1 : 1;
	unsigned char : 6;
} __pmps_bits;

typedef union {
	__pmps_bits bits;
	__sfr_byte byte;
} __pmps_type;

typedef struct {
	unsigned char __rstc0 : 1;
	unsigned char __rstc1 : 1;
	unsigned char __rstc2 : 1;
	unsigned char __rstc3 : 1;
	unsigned char __rstc4 : 1;
	unsigned char __rstc5 : 1;
	unsigned char __rstc6 : 1;
	unsigned char __rstc7 : 1;
} __rstc_bits;

typedef union {
	__rstc_bits bits;
	__sfr_byte byte;
} __rstc_type;

typedef struct {
	unsigned char __vbgren : 1;
	unsigned char : 7;
} __vbgrc_bits;

typedef union {
	__vbgrc_bits bits;
	__sfr_byte byte;
} __vbgrc_type;

typedef struct {
	unsigned char __ptm0pe : 1;
	unsigned char __ptm0ae : 1;
	unsigned char __stm0pe : 1;
	unsigned char __stm0ae : 1;
	unsigned char __ptm0pf : 1;
	unsigned char __ptm0af : 1;
	unsigned char __stm0pf : 1;
	unsigned char __stm0af : 1;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __ptm1pe : 1;
	unsigned char __ptm1ae : 1;
	unsigned char __stm1pe : 1;
	unsigned char __stm1ae : 1;
	unsigned char __ptm1pf : 1;
	unsigned char __ptm1af : 1;
	unsigned char __stm1pf : 1;
	unsigned char __stm1af : 1;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __ptm2pe : 1;
	unsigned char __ptm2ae : 1;
	unsigned char : 2;
	unsigned char __ptm2pf : 1;
	unsigned char __ptm2af : 1;
	unsigned char : 2;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char __spiae : 1;
	unsigned char __sime : 1;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
	unsigned char __spiaf : 1;
	unsigned char __simf : 1;
} __mfi3_bits;

typedef union {
	__mfi3_bits bits;
	__sfr_byte byte;
} __mfi3_type;

typedef struct {
	unsigned char __ptm3pe : 1;
	unsigned char __ptm3ae : 1;
	unsigned char __stm2pe : 1;
	unsigned char __stm2ae : 1;
	unsigned char __ptm3pf : 1;
	unsigned char __ptm3af : 1;
	unsigned char __stm2pf : 1;
	unsigned char __stm2af : 1;
} __mfi4_bits;

typedef union {
	__mfi4_bits bits;
	__sfr_byte byte;
} __mfi4_type;

typedef struct {
	unsigned char __ur0e : 1;
	unsigned char __ur1e : 1;
	unsigned char __ur2e : 1;
	unsigned char : 1;
	unsigned char __ur0f : 1;
	unsigned char __ur1f : 1;
	unsigned char __ur2f : 1;
	unsigned char : 1;
} __mfi5_bits;

typedef union {
	__mfi5_bits bits;
	__sfr_byte byte;
} __mfi5_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char __int2s0 : 1;
	unsigned char __int2s1 : 1;
	unsigned char __int3s0 : 1;
	unsigned char __int3s1 : 1;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __fsiden : 1;
	unsigned char __fhiden : 1;
	unsigned char __fss : 1;
	unsigned char __fhs : 1;
	unsigned char : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __scc_bits;

typedef union {
	__scc_bits bits;
	__sfr_byte byte;
} __scc_type;

typedef struct {
	unsigned char __hircen : 1;
	unsigned char __hircf : 1;
	unsigned char __hirc0 : 1;
	unsigned char __hirc1 : 1;
	unsigned char : 4;
} __hircc_bits;

typedef union {
	__hircc_bits bits;
	__sfr_byte byte;
} __hircc_type;

typedef struct {
	unsigned char __hxten : 1;
	unsigned char __hxtf : 1;
	unsigned char __hxtm : 1;
	unsigned char : 5;
} __hxtc_bits;

typedef union {
	__hxtc_bits bits;
	__sfr_byte byte;
} __hxtc_type;

typedef struct {
	unsigned char __lxten : 1;
	unsigned char __lxtf : 1;
	unsigned char : 6;
} __lxtc_bits;

typedef union {
	__lxtc_bits bits;
	__sfr_byte byte;
} __lxtc_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __lvs0 : 1;
	unsigned char __lvs1 : 1;
	unsigned char __lvs2 : 1;
	unsigned char __lvs3 : 1;
	unsigned char __lvs4 : 1;
	unsigned char __lvs5 : 1;
	unsigned char __lvs6 : 1;
	unsigned char __lvs7 : 1;
} __lvrc_bits;

typedef union {
	__lvrc_bits bits;
	__sfr_byte byte;
} __lvrc_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char __vbgen : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __eeal0 : 1;
	unsigned char __eeal1 : 1;
	unsigned char __eeal2 : 1;
	unsigned char __eeal3 : 1;
	unsigned char __eeal4 : 1;
	unsigned char __eeal5 : 1;
	unsigned char __eeal6 : 1;
	unsigned char __eeal7 : 1;
} __eeal_bits;

typedef union {
	__eeal_bits bits;
	__sfr_byte byte;
} __eeal_type;

typedef struct {
	unsigned char __eeah0 : 1;
	unsigned char __eeah1 : 1;
	unsigned char : 6;
} __eeah_bits;

typedef union {
	__eeah_bits bits;
	__sfr_byte byte;
} __eeah_type;

typedef struct {
	unsigned char : 2;
	unsigned char __cnvt00 : 1;
	unsigned char __cnvt01 : 1;
	unsigned char __c0out : 1;
	unsigned char __c0pol : 1;
	unsigned char __c0en : 1;
	unsigned char : 1;
} __cp0c_bits;

typedef union {
	__cp0c_bits bits;
	__sfr_byte byte;
} __cp0c_type;

typedef struct {
	unsigned char : 2;
	unsigned char __cnvt10 : 1;
	unsigned char __cnvt11 : 1;
	unsigned char __c1out : 1;
	unsigned char __c1pol : 1;
	unsigned char __c1en : 1;
	unsigned char : 1;
} __cp1c_bits;

typedef union {
	__cp1c_bits bits;
	__sfr_byte byte;
} __cp1c_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt0on : 1;
	unsigned char __pt0ck0 : 1;
	unsigned char __pt0ck1 : 1;
	unsigned char __pt0ck2 : 1;
	unsigned char __pt0pau : 1;
} __ptm0c0_bits;

typedef union {
	__ptm0c0_bits bits;
	__sfr_byte byte;
} __ptm0c0_type;

typedef struct {
	unsigned char __pt0cclr : 1;
	unsigned char __pt0capts : 1;
	unsigned char __pt0pol : 1;
	unsigned char __pt0oc : 1;
	unsigned char __pt0io0 : 1;
	unsigned char __pt0io1 : 1;
	unsigned char __pt0m0 : 1;
	unsigned char __pt0m1 : 1;
} __ptm0c1_bits;

typedef union {
	__ptm0c1_bits bits;
	__sfr_byte byte;
} __ptm0c1_type;

typedef struct {
	unsigned char __pt0rp0 : 1;
	unsigned char __pt0rp1 : 1;
	unsigned char __pt0rp2 : 1;
	unsigned char __pt0rp3 : 1;
	unsigned char __pt0rp4 : 1;
	unsigned char __pt0rp5 : 1;
	unsigned char __pt0rp6 : 1;
	unsigned char __pt0rp7 : 1;
} __ptm0rpl_bits;

typedef union {
	__ptm0rpl_bits bits;
	__sfr_byte byte;
} __ptm0rpl_type;

typedef struct {
	unsigned char __pt0rp8 : 1;
	unsigned char __pt0rp9 : 1;
	unsigned char : 6;
} __ptm0rph_bits;

typedef union {
	__ptm0rph_bits bits;
	__sfr_byte byte;
} __ptm0rph_type;

typedef struct {
	unsigned char : 3;
	unsigned char __st0on : 1;
	unsigned char __st0ck0 : 1;
	unsigned char __st0ck1 : 1;
	unsigned char __st0ck2 : 1;
	unsigned char __st0pau : 1;
} __stm0c0_bits;

typedef union {
	__stm0c0_bits bits;
	__sfr_byte byte;
} __stm0c0_type;

typedef struct {
	unsigned char __st0cclr : 1;
	unsigned char __st0dpx : 1;
	unsigned char __st0pol : 1;
	unsigned char __st0oc : 1;
	unsigned char __st0io0 : 1;
	unsigned char __st0io1 : 1;
	unsigned char __st0m0 : 1;
	unsigned char __st0m1 : 1;
} __stm0c1_bits;

typedef union {
	__stm0c1_bits bits;
	__sfr_byte byte;
} __stm0c1_type;

typedef struct {
	unsigned char __st0rp0 : 1;
	unsigned char __st0rp1 : 1;
	unsigned char __st0rp2 : 1;
	unsigned char __st0rp3 : 1;
	unsigned char __st0rp4 : 1;
	unsigned char __st0rp5 : 1;
	unsigned char __st0rp6 : 1;
	unsigned char __st0rp7 : 1;
} __stm0rp_bits;

typedef union {
	__stm0rp_bits bits;
	__sfr_byte byte;
} __stm0rp_type;

typedef struct {
	unsigned char __sledc00 : 1;
	unsigned char __sledc01 : 1;
	unsigned char __sledc02 : 1;
	unsigned char __sledc03 : 1;
	unsigned char __sledc04 : 1;
	unsigned char __sledc05 : 1;
	unsigned char __sledc06 : 1;
	unsigned char __sledc07 : 1;
} __sledc0_bits;

typedef union {
	__sledc0_bits bits;
	__sfr_byte byte;
} __sledc0_type;

typedef struct {
	unsigned char __sledc10 : 1;
	unsigned char __sledc11 : 1;
	unsigned char __sledc12 : 1;
	unsigned char __sledc13 : 1;
	unsigned char __sledc14 : 1;
	unsigned char __sledc15 : 1;
	unsigned char __sledc16 : 1;
	unsigned char __sledc17 : 1;
} __sledc1_bits;

typedef union {
	__sledc1_bits bits;
	__sfr_byte byte;
} __sledc1_type;

typedef struct {
	unsigned char __sledc20 : 1;
	unsigned char __sledc21 : 1;
	unsigned char __sledc22 : 1;
	unsigned char __sledc23 : 1;
	unsigned char __sledc24 : 1;
	unsigned char __sledc25 : 1;
	unsigned char __sledc26 : 1;
	unsigned char __sledc27 : 1;
} __sledc2_bits;

typedef union {
	__sledc2_bits bits;
	__sfr_byte byte;
} __sledc2_type;

typedef struct {
	unsigned char __sledc30 : 1;
	unsigned char __sledc31 : 1;
	unsigned char __sledc32 : 1;
	unsigned char __sledc33 : 1;
	unsigned char __sledc34 : 1;
	unsigned char __sledc35 : 1;
	unsigned char __sledc36 : 1;
	unsigned char __sledc37 : 1;
} __sledc3_bits;

typedef union {
	__sledc3_bits bits;
	__sfr_byte byte;
} __sledc3_type;

typedef struct {
	unsigned char : 6;
	unsigned char __mdwov : 1;
	unsigned char __mdwef : 1;
} __mduwctrl_bits;

typedef union {
	__mduwctrl_bits bits;
	__sfr_byte byte;
} __mduwctrl_type;

typedef struct {
	unsigned char __c0of0 : 1;
	unsigned char __c0of1 : 1;
	unsigned char __c0of2 : 1;
	unsigned char __c0of3 : 1;
	unsigned char __c0of4 : 1;
	unsigned char __c0rsp : 1;
	unsigned char __c0ofm : 1;
	unsigned char : 1;
} __cp0vos_bits;

typedef union {
	__cp0vos_bits bits;
	__sfr_byte byte;
} __cp0vos_type;

typedef struct {
	unsigned char __c1of0 : 1;
	unsigned char __c1of1 : 1;
	unsigned char __c1of2 : 1;
	unsigned char __c1of3 : 1;
	unsigned char __c1of4 : 1;
	unsigned char __c1rsp : 1;
	unsigned char __c1ofm : 1;
	unsigned char : 1;
} __cp1vos_bits;

typedef union {
	__cp1vos_bits bits;
	__sfr_byte byte;
} __cp1vos_type;

typedef struct {
	unsigned char __clksel00 : 1;
	unsigned char __clksel01 : 1;
	unsigned char : 6;
} __psc0r_bits;

typedef union {
	__psc0r_bits bits;
	__sfr_byte byte;
} __psc0r_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tb0c_bits;

typedef union {
	__tb0c_bits bits;
	__sfr_byte byte;
} __tb0c_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tb1c_bits;

typedef union {
	__tb1c_bits bits;
	__sfr_byte byte;
} __tb1c_type;

typedef struct {
	unsigned char __clksel10 : 1;
	unsigned char __clksel11 : 1;
	unsigned char : 6;
} __psc1r_bits;

typedef union {
	__psc1r_bits bits;
	__sfr_byte byte;
} __psc1r_type;

typedef struct {
	unsigned char __sacs0 : 1;
	unsigned char __sacs1 : 1;
	unsigned char __sacs2 : 1;
	unsigned char __sacs3 : 1;
	unsigned char __adrfs : 1;
	unsigned char __adcen : 1;
	unsigned char __adbz : 1;
	unsigned char __start : 1;
} __sadc0_bits;

typedef union {
	__sadc0_bits bits;
	__sfr_byte byte;
} __sadc0_type;

typedef struct {
	unsigned char __sacks0 : 1;
	unsigned char __sacks1 : 1;
	unsigned char __sacks2 : 1;
	unsigned char : 1;
	unsigned char __sains0 : 1;
	unsigned char __sains1 : 1;
	unsigned char __sains2 : 1;
	unsigned char __sains3 : 1;
} __sadc1_bits;

typedef union {
	__sadc1_bits bits;
	__sfr_byte byte;
} __sadc1_type;

typedef struct {
	unsigned char __pgags0 : 1;
	unsigned char __pgags1 : 1;
	unsigned char __savrs0 : 1;
	unsigned char __savrs1 : 1;
	unsigned char __pgais : 1;
	unsigned char : 2;
	unsigned char __adpgaen : 1;
} __sadc2_bits;

typedef union {
	__sadc2_bits bits;
	__sfr_byte byte;
} __sadc2_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char : 1;
	unsigned char __iica0 : 1;
	unsigned char __iica1 : 1;
	unsigned char __iica2 : 1;
	unsigned char __iica3 : 1;
	unsigned char __iica4 : 1;
	unsigned char __iica5 : 1;
	unsigned char __iica6 : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __spiaicf : 1;
	unsigned char __spiaen : 1;
	unsigned char : 3;
	unsigned char __saspi0 : 1;
	unsigned char __saspi1 : 1;
	unsigned char __saspi2 : 1;
} __spiac0_bits;

typedef union {
	__spiac0_bits bits;
	__sfr_byte byte;
} __spiac0_type;

typedef struct {
	unsigned char __satrf : 1;
	unsigned char __sawcol : 1;
	unsigned char __sacsen : 1;
	unsigned char __samls : 1;
	unsigned char __sackeg : 1;
	unsigned char __sackpolb : 1;
	unsigned char : 2;
} __spiac1_bits;

typedef union {
	__spiac1_bits bits;
	__sfr_byte byte;
} __spiac1_type;

typedef struct {
	unsigned char __a0 : 1;
	unsigned char __a1 : 1;
	unsigned char __a2 : 1;
	unsigned char __a3 : 1;
	unsigned char __a4 : 1;
	unsigned char __a5 : 1;
	unsigned char __a6 : 1;
	unsigned char __a7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __a8 : 1;
	unsigned char __a9 : 1;
	unsigned char __a10 : 1;
	unsigned char __a11 : 1;
	unsigned char __a12 : 1;
	unsigned char __a13 : 1;
	unsigned char __a14 : 1;
	unsigned char __a15 : 1;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char : 4;
	unsigned char __scomen : 1;
	unsigned char __isel0 : 1;
	unsigned char __isel1 : 1;
	unsigned char : 1;
} __scomc_bits;

typedef union {
	__scomc_bits bits;
	__sfr_byte byte;
} __scomc_type;

typedef struct {
	unsigned char __poly : 1;
	unsigned char : 7;
} __crccr_bits;

typedef union {
	__crccr_bits bits;
	__sfr_byte byte;
} __crccr_type;

typedef struct {
	unsigned char __iecs0 : 1;
	unsigned char __iecs1 : 1;
	unsigned char __iecs2 : 1;
	unsigned char __iecs3 : 1;
	unsigned char __iecs4 : 1;
	unsigned char __iecs5 : 1;
	unsigned char __iecs6 : 1;
	unsigned char __iecs7 : 1;
} __iecc_bits;

typedef union {
	__iecc_bits bits;
	__sfr_byte byte;
} __iecc_type;

typedef struct {
	unsigned char __txif2 : 1;
	unsigned char __tidle2 : 1;
	unsigned char __rxif2 : 1;
	unsigned char __ridle2 : 1;
	unsigned char __oerr2 : 1;
	unsigned char __ferr2 : 1;
	unsigned char __nf2 : 1;
	unsigned char __perr2 : 1;
} __u2sr_bits;

typedef union {
	__u2sr_bits bits;
	__sfr_byte byte;
} __u2sr_type;

typedef struct {
	unsigned char __tx82 : 1;
	unsigned char __rx82 : 1;
	unsigned char __txbrk2 : 1;
	unsigned char __stops2 : 1;
	unsigned char __prt2 : 1;
	unsigned char __pren2 : 1;
	unsigned char __bno2 : 1;
	unsigned char __uarten2 : 1;
} __u2cr1_bits;

typedef union {
	__u2cr1_bits bits;
	__sfr_byte byte;
} __u2cr1_type;

typedef struct {
	unsigned char __teie2 : 1;
	unsigned char __tiie2 : 1;
	unsigned char __rie2 : 1;
	unsigned char __wake2 : 1;
	unsigned char __adden2 : 1;
	unsigned char __brgh2 : 1;
	unsigned char __rxen2 : 1;
	unsigned char __txen2 : 1;
} __u2cr2_bits;

typedef union {
	__u2cr2_bits bits;
	__sfr_byte byte;
} __u2cr2_type;

typedef struct {
	unsigned char __txif0 : 1;
	unsigned char __tidle0 : 1;
	unsigned char __rxif0 : 1;
	unsigned char __ridle0 : 1;
	unsigned char __oerr0 : 1;
	unsigned char __ferr0 : 1;
	unsigned char __nf0 : 1;
	unsigned char __perr0 : 1;
} __u0sr_bits;

typedef union {
	__u0sr_bits bits;
	__sfr_byte byte;
} __u0sr_type;

typedef struct {
	unsigned char __tx80 : 1;
	unsigned char __rx80 : 1;
	unsigned char __txbrk0 : 1;
	unsigned char __stops0 : 1;
	unsigned char __prt0 : 1;
	unsigned char __pren0 : 1;
	unsigned char __bno0 : 1;
	unsigned char __uarten0 : 1;
} __u0cr1_bits;

typedef union {
	__u0cr1_bits bits;
	__sfr_byte byte;
} __u0cr1_type;

typedef struct {
	unsigned char __teie0 : 1;
	unsigned char __tiie0 : 1;
	unsigned char __rie0 : 1;
	unsigned char __wake0 : 1;
	unsigned char __adden0 : 1;
	unsigned char __brgh0 : 1;
	unsigned char __rxen0 : 1;
	unsigned char __txen0 : 1;
} __u0cr2_bits;

typedef union {
	__u0cr2_bits bits;
	__sfr_byte byte;
} __u0cr2_type;

typedef struct {
	unsigned char __txif1 : 1;
	unsigned char __tidle1 : 1;
	unsigned char __rxif1 : 1;
	unsigned char __ridle1 : 1;
	unsigned char __oerr1 : 1;
	unsigned char __ferr1 : 1;
	unsigned char __nf1 : 1;
	unsigned char __perr1 : 1;
} __u1sr_bits;

typedef union {
	__u1sr_bits bits;
	__sfr_byte byte;
} __u1sr_type;

typedef struct {
	unsigned char __tx81 : 1;
	unsigned char __rx81 : 1;
	unsigned char __txbrk1 : 1;
	unsigned char __stops1 : 1;
	unsigned char __prt1 : 1;
	unsigned char __pren1 : 1;
	unsigned char __bno1 : 1;
	unsigned char __uarten1 : 1;
} __u1cr1_bits;

typedef union {
	__u1cr1_bits bits;
	__sfr_byte byte;
} __u1cr1_type;

typedef struct {
	unsigned char __teie1 : 1;
	unsigned char __tiie1 : 1;
	unsigned char __rie1 : 1;
	unsigned char __wake1 : 1;
	unsigned char __adden1 : 1;
	unsigned char __brgh1 : 1;
	unsigned char __rxen1 : 1;
	unsigned char __txen1 : 1;
} __u1cr2_bits;

typedef union {
	__u1cr2_bits bits;
	__sfr_byte byte;
} __u1cr2_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt1on : 1;
	unsigned char __pt1ck0 : 1;
	unsigned char __pt1ck1 : 1;
	unsigned char __pt1ck2 : 1;
	unsigned char __pt1pau : 1;
} __ptm1c0_bits;

typedef union {
	__ptm1c0_bits bits;
	__sfr_byte byte;
} __ptm1c0_type;

typedef struct {
	unsigned char __pt1cclr : 1;
	unsigned char __pt1capts : 1;
	unsigned char __pt1pol : 1;
	unsigned char __pt1oc : 1;
	unsigned char __pt1io0 : 1;
	unsigned char __pt1io1 : 1;
	unsigned char __pt1m0 : 1;
	unsigned char __pt1m1 : 1;
} __ptm1c1_bits;

typedef union {
	__ptm1c1_bits bits;
	__sfr_byte byte;
} __ptm1c1_type;

typedef struct {
	unsigned char __pt1rp0 : 1;
	unsigned char __pt1rp1 : 1;
	unsigned char __pt1rp2 : 1;
	unsigned char __pt1rp3 : 1;
	unsigned char __pt1rp4 : 1;
	unsigned char __pt1rp5 : 1;
	unsigned char __pt1rp6 : 1;
	unsigned char __pt1rp7 : 1;
} __ptm1rpl_bits;

typedef union {
	__ptm1rpl_bits bits;
	__sfr_byte byte;
} __ptm1rpl_type;

typedef struct {
	unsigned char __pt1rp8 : 1;
	unsigned char __pt1rp9 : 1;
	unsigned char : 6;
} __ptm1rph_bits;

typedef union {
	__ptm1rph_bits bits;
	__sfr_byte byte;
} __ptm1rph_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt2on : 1;
	unsigned char __pt2ck0 : 1;
	unsigned char __pt2ck1 : 1;
	unsigned char __pt2ck2 : 1;
	unsigned char __pt2pau : 1;
} __ptm2c0_bits;

typedef union {
	__ptm2c0_bits bits;
	__sfr_byte byte;
} __ptm2c0_type;

typedef struct {
	unsigned char __pt2cclr : 1;
	unsigned char __pt2capts : 1;
	unsigned char __pt2pol : 1;
	unsigned char __pt2oc : 1;
	unsigned char __pt2io0 : 1;
	unsigned char __pt2io1 : 1;
	unsigned char __pt2m0 : 1;
	unsigned char __pt2m1 : 1;
} __ptm2c1_bits;

typedef union {
	__ptm2c1_bits bits;
	__sfr_byte byte;
} __ptm2c1_type;

typedef struct {
	unsigned char __pt2rp0 : 1;
	unsigned char __pt2rp1 : 1;
	unsigned char __pt2rp2 : 1;
	unsigned char __pt2rp3 : 1;
	unsigned char __pt2rp4 : 1;
	unsigned char __pt2rp5 : 1;
	unsigned char __pt2rp6 : 1;
	unsigned char __pt2rp7 : 1;
} __ptm2rpl_bits;

typedef union {
	__ptm2rpl_bits bits;
	__sfr_byte byte;
} __ptm2rpl_type;

typedef struct {
	unsigned char __pt2rp8 : 1;
	unsigned char __pt2rp9 : 1;
	unsigned char __pt2rp10 : 1;
	unsigned char __pt2rp11 : 1;
	unsigned char __pt2rp12 : 1;
	unsigned char __pt2rp13 : 1;
	unsigned char __pt2rp14 : 1;
	unsigned char __pt2rp15 : 1;
} __ptm2rph_bits;

typedef union {
	__ptm2rph_bits bits;
	__sfr_byte byte;
} __ptm2rph_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt3on : 1;
	unsigned char __pt3ck0 : 1;
	unsigned char __pt3ck1 : 1;
	unsigned char __pt3ck2 : 1;
	unsigned char __pt3pau : 1;
} __ptm3c0_bits;

typedef union {
	__ptm3c0_bits bits;
	__sfr_byte byte;
} __ptm3c0_type;

typedef struct {
	unsigned char __pt3cclr : 1;
	unsigned char __pt3capts : 1;
	unsigned char __pt3pol : 1;
	unsigned char __pt3oc : 1;
	unsigned char __pt3io0 : 1;
	unsigned char __pt3io1 : 1;
	unsigned char __pt3m0 : 1;
	unsigned char __pt3m1 : 1;
} __ptm3c1_bits;

typedef union {
	__ptm3c1_bits bits;
	__sfr_byte byte;
} __ptm3c1_type;

typedef struct {
	unsigned char __pt3rp0 : 1;
	unsigned char __pt3rp1 : 1;
	unsigned char __pt3rp2 : 1;
	unsigned char __pt3rp3 : 1;
	unsigned char __pt3rp4 : 1;
	unsigned char __pt3rp5 : 1;
	unsigned char __pt3rp6 : 1;
	unsigned char __pt3rp7 : 1;
} __ptm3rpl_bits;

typedef union {
	__ptm3rpl_bits bits;
	__sfr_byte byte;
} __ptm3rpl_type;

typedef struct {
	unsigned char __pt3rp8 : 1;
	unsigned char __pt3rp9 : 1;
	unsigned char __pt3rp10 : 1;
	unsigned char __pt3rp11 : 1;
	unsigned char __pt3rp12 : 1;
	unsigned char __pt3rp13 : 1;
	unsigned char __pt3rp14 : 1;
	unsigned char __pt3rp15 : 1;
} __ptm3rph_bits;

typedef union {
	__ptm3rph_bits bits;
	__sfr_byte byte;
} __ptm3rph_type;

typedef struct {
	unsigned char : 3;
	unsigned char __st1on : 1;
	unsigned char __st1ck0 : 1;
	unsigned char __st1ck1 : 1;
	unsigned char __st1ck2 : 1;
	unsigned char __st1pau : 1;
} __stm1c0_bits;

typedef union {
	__stm1c0_bits bits;
	__sfr_byte byte;
} __stm1c0_type;

typedef struct {
	unsigned char __st1cclr : 1;
	unsigned char __st1dpx : 1;
	unsigned char __st1pol : 1;
	unsigned char __st1oc : 1;
	unsigned char __st1io0 : 1;
	unsigned char __st1io1 : 1;
	unsigned char __st1m0 : 1;
	unsigned char __st1m1 : 1;
} __stm1c1_bits;

typedef union {
	__stm1c1_bits bits;
	__sfr_byte byte;
} __stm1c1_type;

typedef struct {
	unsigned char __st1rp0 : 1;
	unsigned char __st1rp1 : 1;
	unsigned char __st1rp2 : 1;
	unsigned char __st1rp3 : 1;
	unsigned char __st1rp4 : 1;
	unsigned char __st1rp5 : 1;
	unsigned char __st1rp6 : 1;
	unsigned char __st1rp7 : 1;
} __stm1rp_bits;

typedef union {
	__stm1rp_bits bits;
	__sfr_byte byte;
} __stm1rp_type;

typedef struct {
	unsigned char : 3;
	unsigned char __st2on : 1;
	unsigned char __st2ck0 : 1;
	unsigned char __st2ck1 : 1;
	unsigned char __st2ck2 : 1;
	unsigned char __st2pau : 1;
} __stm2c0_bits;

typedef union {
	__stm2c0_bits bits;
	__sfr_byte byte;
} __stm2c0_type;

typedef struct {
	unsigned char __st2cclr : 1;
	unsigned char __st2dpx : 1;
	unsigned char __st2pol : 1;
	unsigned char __st2oc : 1;
	unsigned char __st2io0 : 1;
	unsigned char __st2io1 : 1;
	unsigned char __st2m0 : 1;
	unsigned char __st2m1 : 1;
} __stm2c1_bits;

typedef union {
	__stm2c1_bits bits;
	__sfr_byte byte;
} __stm2c1_type;

typedef struct {
	unsigned char __st2rp0 : 1;
	unsigned char __st2rp1 : 1;
	unsigned char __st2rp2 : 1;
	unsigned char __st2rp3 : 1;
	unsigned char __st2rp4 : 1;
	unsigned char __st2rp5 : 1;
	unsigned char __st2rp6 : 1;
	unsigned char __st2rp7 : 1;
} __stm2rp_bits;

typedef union {
	__stm2rp_bits bits;
	__sfr_byte byte;
} __stm2rp_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __clwb : 1;
	unsigned char : 7;
} __fc2_bits;

typedef union {
	__fc2_bits bits;
	__sfr_byte byte;
} __fc2_type;

typedef struct {
	unsigned char __stck0ps : 1;
	unsigned char __stck1ps : 1;
	unsigned char __stck2ps : 1;
	unsigned char __ptck0ps : 1;
	unsigned char __ptck1ps : 1;
	unsigned char __ptck2ps : 1;
	unsigned char __ptck3ps : 1;
	unsigned char : 1;
} __ifs0_bits;

typedef union {
	__ifs0_bits bits;
	__sfr_byte byte;
} __ifs0_type;

typedef struct {
	unsigned char __stp0ips : 1;
	unsigned char __stp1ips : 1;
	unsigned char __stp2ips : 1;
	unsigned char __ptp0ips : 1;
	unsigned char __ptp1ips : 1;
	unsigned char __ptp2ips : 1;
	unsigned char __ptp3ips : 1;
	unsigned char : 1;
} __ifs1_bits;

typedef union {
	__ifs1_bits bits;
	__sfr_byte byte;
} __ifs1_type;

typedef struct {
	unsigned char __int0ps : 1;
	unsigned char __int1ps : 1;
	unsigned char __int2ps : 1;
	unsigned char __int3ps : 1;
	unsigned char __scksclps : 1;
	unsigned char __sdisdaps : 1;
	unsigned char __scsbps : 1;
	unsigned char : 1;
} __ifs2_bits;

typedef union {
	__ifs2_bits bits;
	__sfr_byte byte;
} __ifs2_type;

typedef struct {
	unsigned char __rx0ps : 1;
	unsigned char __rx1ps : 1;
	unsigned char __rx2ps : 1;
	unsigned char : 5;
} __ifs3_bits;

typedef union {
	__ifs3_bits bits;
	__sfr_byte byte;
} __ifs3_type;

typedef struct {
	unsigned char __pas00 : 1;
	unsigned char __pas01 : 1;
	unsigned char __pas02 : 1;
	unsigned char __pas03 : 1;
	unsigned char __pas04 : 1;
	unsigned char __pas05 : 1;
	unsigned char __pas06 : 1;
	unsigned char __pas07 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char __pas10 : 1;
	unsigned char __pas11 : 1;
	unsigned char __pas12 : 1;
	unsigned char __pas13 : 1;
	unsigned char __pas14 : 1;
	unsigned char __pas15 : 1;
	unsigned char __pas16 : 1;
	unsigned char __pas17 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pbs00 : 1;
	unsigned char __pbs01 : 1;
	unsigned char __pbs02 : 1;
	unsigned char __pbs03 : 1;
	unsigned char __pbs04 : 1;
	unsigned char __pbs05 : 1;
	unsigned char __pbs06 : 1;
	unsigned char __pbs07 : 1;
} __pbs0_bits;

typedef union {
	__pbs0_bits bits;
	__sfr_byte byte;
} __pbs0_type;

typedef struct {
	unsigned char __pbs10 : 1;
	unsigned char __pbs11 : 1;
	unsigned char __pbs12 : 1;
	unsigned char __pbs13 : 1;
	unsigned char __pbs14 : 1;
	unsigned char __pbs15 : 1;
	unsigned char __pbs16 : 1;
	unsigned char __pbs17 : 1;
} __pbs1_bits;

typedef union {
	__pbs1_bits bits;
	__sfr_byte byte;
} __pbs1_type;

typedef struct {
	unsigned char __pcs00 : 1;
	unsigned char __pcs01 : 1;
	unsigned char __pcs02 : 1;
	unsigned char __pcs03 : 1;
	unsigned char __pcs04 : 1;
	unsigned char __pcs05 : 1;
	unsigned char __pcs06 : 1;
	unsigned char __pcs07 : 1;
} __pcs0_bits;

typedef union {
	__pcs0_bits bits;
	__sfr_byte byte;
} __pcs0_type;

typedef struct {
	unsigned char __pcs10 : 1;
	unsigned char __pcs11 : 1;
	unsigned char __pcs12 : 1;
	unsigned char __pcs13 : 1;
	unsigned char __pcs14 : 1;
	unsigned char __pcs15 : 1;
	unsigned char __pcs16 : 1;
	unsigned char __pcs17 : 1;
} __pcs1_bits;

typedef union {
	__pcs1_bits bits;
	__sfr_byte byte;
} __pcs1_type;

typedef struct {
	unsigned char __pds00 : 1;
	unsigned char __pds01 : 1;
	unsigned char __pds02 : 1;
	unsigned char __pds03 : 1;
	unsigned char __pds04 : 1;
	unsigned char __pds05 : 1;
	unsigned char __pds06 : 1;
	unsigned char __pds07 : 1;
} __pds0_bits;

typedef union {
	__pds0_bits bits;
	__sfr_byte byte;
} __pds0_type;

typedef struct {
	unsigned char __pds10 : 1;
	unsigned char __pds11 : 1;
	unsigned char __pds12 : 1;
	unsigned char __pds13 : 1;
	unsigned char __pds14 : 1;
	unsigned char __pds15 : 1;
	unsigned char : 2;
} __pds1_bits;

typedef union {
	__pds1_bits bits;
	__sfr_byte byte;
} __pds1_type;

typedef struct {
	unsigned char __pes00 : 1;
	unsigned char __pes01 : 1;
	unsigned char __pes02 : 1;
	unsigned char __pes03 : 1;
	unsigned char __pes04 : 1;
	unsigned char __pes05 : 1;
	unsigned char __pes06 : 1;
	unsigned char __pes07 : 1;
} __pes0_bits;

typedef union {
	__pes0_bits bits;
	__sfr_byte byte;
} __pes0_type;

typedef struct {
	unsigned char __pes10 : 1;
	unsigned char __pes11 : 1;
	unsigned char : 6;
} __pes1_bits;

typedef union {
	__pes1_bits bits;
	__sfr_byte byte;
} __pes1_type;

typedef struct {
	unsigned char __pfs00 : 1;
	unsigned char __pfs01 : 1;
	unsigned char __pfs02 : 1;
	unsigned char __pfs03 : 1;
	unsigned char __pfs04 : 1;
	unsigned char __pfs05 : 1;
	unsigned char __pfs06 : 1;
	unsigned char __pfs07 : 1;
} __pfs0_bits;

typedef union {
	__pfs0_bits bits;
	__sfr_byte byte;
} __pfs0_type;

typedef struct {
	unsigned char __pfs10 : 1;
	unsigned char __pfs11 : 1;
	unsigned char __pfs12 : 1;
	unsigned char __pfs13 : 1;
	unsigned char __pfs14 : 1;
	unsigned char __pfs15 : 1;
	unsigned char __pfs16 : 1;
	unsigned char __pfs17 : 1;
} __pfs1_bits;

typedef union {
	__pfs1_bits bits;
	__sfr_byte byte;
} __pfs1_type;

typedef struct {
	unsigned char __pgs00 : 1;
	unsigned char __pgs01 : 1;
	unsigned char __pgs02 : 1;
	unsigned char __pgs03 : 1;
	unsigned char __pgs04 : 1;
	unsigned char __pgs05 : 1;
	unsigned char __pgs06 : 1;
	unsigned char __pgs07 : 1;
} __pgs0_bits;

typedef union {
	__pgs0_bits bits;
	__sfr_byte byte;
} __pgs0_type;

typedef struct {
	unsigned char __pgs10 : 1;
	unsigned char __pgs11 : 1;
	unsigned char __pgs12 : 1;
	unsigned char __pgs13 : 1;
	unsigned char __pgs14 : 1;
	unsigned char __pgs15 : 1;
	unsigned char __pgs16 : 1;
	unsigned char __pgs17 : 1;
} __pgs1_bits;

typedef union {
	__pgs1_bits bits;
	__sfr_byte byte;
} __pgs1_type;

typedef struct {
	unsigned char __phs00 : 1;
	unsigned char __phs01 : 1;
	unsigned char __phs02 : 1;
	unsigned char __phs03 : 1;
	unsigned char __phs04 : 1;
	unsigned char __phs05 : 1;
	unsigned char __phs06 : 1;
	unsigned char __phs07 : 1;
} __phs0_bits;

typedef union {
	__phs0_bits bits;
	__sfr_byte byte;
} __phs0_type;

typedef struct {
	unsigned char __phs10 : 1;
	unsigned char __phs11 : 1;
	unsigned char __phs12 : 1;
	unsigned char __phs13 : 1;
	unsigned char : 4;
} __phs1_bits;

typedef union {
	__phs1_bits bits;
	__sfr_byte byte;
} __phs1_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1l, 0x03);
DEFINE_SFR(__sfr_byte, __mp1h, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__sfr_byte, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__pbp_type, __pbp, 0x0b);
DEFINE_SFR(__sfr_byte, __mp2l, 0x0d);
DEFINE_SFR(__sfr_byte, __mp2h, 0x0e);
DEFINE_SFR(__rstfc_type, __rstfc, 0x0f);
DEFINE_SFR(__intc0_type, __intc0, 0x10);
DEFINE_SFR(__intc1_type, __intc1, 0x11);
DEFINE_SFR(__intc2_type, __intc2, 0x12);
DEFINE_SFR(__intc3_type, __intc3, 0x13);
DEFINE_SFR(__pa_type, __pa, 0x14);
DEFINE_SFR(__pac_type, __pac, 0x15);
DEFINE_SFR(__papu_type, __papu, 0x16);
DEFINE_SFR(__pawu_type, __pawu, 0x17);
DEFINE_SFR(__pb_type, __pb, 0x18);
DEFINE_SFR(__pbc_type, __pbc, 0x19);
DEFINE_SFR(__pbpu_type, __pbpu, 0x1a);
DEFINE_SFR(__pc_type, __pc, 0x1b);
DEFINE_SFR(__pcc_type, __pcc, 0x1c);
DEFINE_SFR(__pcpu_type, __pcpu, 0x1d);
DEFINE_SFR(__pd_type, __pd, 0x1e);
DEFINE_SFR(__pdc_type, __pdc, 0x1f);
DEFINE_SFR(__pdpu_type, __pdpu, 0x20);
DEFINE_SFR(__pe_type, __pe, 0x21);
DEFINE_SFR(__pec_type, __pec, 0x22);
DEFINE_SFR(__pepu_type, __pepu, 0x23);
DEFINE_SFR(__pf_type, __pf, 0x24);
DEFINE_SFR(__pfc_type, __pfc, 0x25);
DEFINE_SFR(__pfpu_type, __pfpu, 0x26);
DEFINE_SFR(__pg_type, __pg, 0x27);
DEFINE_SFR(__pgc_type, __pgc, 0x28);
DEFINE_SFR(__pgpu_type, __pgpu, 0x29);
DEFINE_SFR(__ph_type, __ph, 0x2a);
DEFINE_SFR(__phc_type, __phc, 0x2b);
DEFINE_SFR(__phpu_type, __phpu, 0x2c);
DEFINE_SFR(__pmps_type, __pmps, 0x2d);
DEFINE_SFR(__rstc_type, __rstc, 0x2e);
DEFINE_SFR(__vbgrc_type, __vbgrc, 0x2f);
DEFINE_SFR(__mfi0_type, __mfi0, 0x33);
DEFINE_SFR(__mfi1_type, __mfi1, 0x34);
DEFINE_SFR(__mfi2_type, __mfi2, 0x35);
DEFINE_SFR(__mfi3_type, __mfi3, 0x36);
DEFINE_SFR(__mfi4_type, __mfi4, 0x37);
DEFINE_SFR(__mfi5_type, __mfi5, 0x38);
DEFINE_SFR(__integ_type, __integ, 0x39);
DEFINE_SFR(__scc_type, __scc, 0x3a);
DEFINE_SFR(__hircc_type, __hircc, 0x3b);
DEFINE_SFR(__hxtc_type, __hxtc, 0x3c);
DEFINE_SFR(__lxtc_type, __lxtc, 0x3d);
DEFINE_SFR(__wdtc_type, __wdtc, 0x3e);
DEFINE_SFR(__lvrc_type, __lvrc, 0x3f);
DEFINE_SFR(__lvdc_type, __lvdc, 0x40);
DEFINE_SFR(__eeal_type, __eeal, 0x41);
DEFINE_SFR(__eeah_type, __eeah, 0x42);
DEFINE_SFR(__sfr_byte, __eed, 0x43);
DEFINE_SFR(__cp0c_type, __cp0c, 0x44);
DEFINE_SFR(__cp1c_type, __cp1c, 0x45);
DEFINE_SFR(__ptm0c0_type, __ptm0c0, 0x46);
DEFINE_SFR(__ptm0c1_type, __ptm0c1, 0x47);
DEFINE_SFR(__sfr_byte, __ptm0dl, 0x48);
DEFINE_SFR(__sfr_byte, __ptm0dh, 0x49);
DEFINE_SFR(__sfr_byte, __ptm0al, 0x4a);
DEFINE_SFR(__sfr_byte, __ptm0ah, 0x4b);
DEFINE_SFR(__ptm0rpl_type, __ptm0rpl, 0x4c);
DEFINE_SFR(__ptm0rph_type, __ptm0rph, 0x4d);
DEFINE_SFR(__stm0c0_type, __stm0c0, 0x4e);
DEFINE_SFR(__stm0c1_type, __stm0c1, 0x4f);
DEFINE_SFR(__sfr_byte, __stm0dl, 0x50);
DEFINE_SFR(__sfr_byte, __stm0dh, 0x51);
DEFINE_SFR(__sfr_byte, __stm0al, 0x52);
DEFINE_SFR(__sfr_byte, __stm0ah, 0x53);
DEFINE_SFR(__stm0rp_type, __stm0rp, 0x54);
DEFINE_SFR(__sledc0_type, __sledc0, 0x55);
DEFINE_SFR(__sledc1_type, __sledc1, 0x56);
DEFINE_SFR(__sledc2_type, __sledc2, 0x57);
DEFINE_SFR(__sledc3_type, __sledc3, 0x58);
DEFINE_SFR(__sfr_byte, __mduwr0, 0x59);
DEFINE_SFR(__sfr_byte, __mduwr1, 0x5a);
DEFINE_SFR(__sfr_byte, __mduwr2, 0x5b);
DEFINE_SFR(__sfr_byte, __mduwr3, 0x5c);
DEFINE_SFR(__sfr_byte, __mduwr4, 0x5d);
DEFINE_SFR(__sfr_byte, __mduwr5, 0x5e);
DEFINE_SFR(__mduwctrl_type, __mduwctrl, 0x5f);
DEFINE_SFR(__cp0vos_type, __cp0vos, 0x60);
DEFINE_SFR(__cp1vos_type, __cp1vos, 0x61);
DEFINE_SFR(__psc0r_type, __psc0r, 0x63);
DEFINE_SFR(__tb0c_type, __tb0c, 0x64);
DEFINE_SFR(__tb1c_type, __tb1c, 0x65);
DEFINE_SFR(__psc1r_type, __psc1r, 0x66);
DEFINE_SFR(__sfr_byte, __sadol, 0x67);
DEFINE_SFR(__sfr_byte, __sadoh, 0x68);
DEFINE_SFR(__sadc0_type, __sadc0, 0x69);
DEFINE_SFR(__sadc1_type, __sadc1, 0x6a);
DEFINE_SFR(__sadc2_type, __sadc2, 0x6b);
DEFINE_SFR(__simc0_type, __simc0, 0x6c);
DEFINE_SFR(__simc1_type, __simc1, 0x6d);
DEFINE_SFR(__sfr_byte, __simd, 0x6e);
DEFINE_SFR(__simc2_type, __simc2, 0x6f);
DEFINE_SFR(__sima_type, __sima, 0x6f);
DEFINE_SFR(__simtoc_type, __simtoc, 0x70);
DEFINE_SFR(__spiac0_type, __spiac0, 0x71);
DEFINE_SFR(__spiac1_type, __spiac1, 0x72);
DEFINE_SFR(__sfr_byte, __spiad, 0x73);
DEFINE_SFR(__farl_type, __farl, 0x74);
DEFINE_SFR(__farh_type, __farh, 0x75);
DEFINE_SFR(__sfr_byte, __fd0l, 0x76);
DEFINE_SFR(__sfr_byte, __fd0h, 0x77);
DEFINE_SFR(__sfr_byte, __fd1l, 0x78);
DEFINE_SFR(__sfr_byte, __fd1h, 0x79);
DEFINE_SFR(__sfr_byte, __fd2l, 0x7a);
DEFINE_SFR(__sfr_byte, __fd2h, 0x7b);
DEFINE_SFR(__sfr_byte, __fd3l, 0x7c);
DEFINE_SFR(__sfr_byte, __fd3h, 0x7d);
DEFINE_SFR(__scomc_type, __scomc, 0x7f);
DEFINE_SFR(__crccr_type, __crccr, 0x100);
DEFINE_SFR(__sfr_byte, __crcin, 0x101);
DEFINE_SFR(__sfr_byte, __crcdl, 0x102);
DEFINE_SFR(__sfr_byte, __crcdh, 0x103);
DEFINE_SFR(__iecc_type, __iecc, 0x106);
DEFINE_SFR(__u2sr_type, __u2sr, 0x10b);
DEFINE_SFR(__u2cr1_type, __u2cr1, 0x10c);
DEFINE_SFR(__u2cr2_type, __u2cr2, 0x10d);
DEFINE_SFR(__sfr_byte, __txr_rxr2, 0x10e);
DEFINE_SFR(__sfr_byte, __brg2, 0x10f);
DEFINE_SFR(__u0sr_type, __u0sr, 0x110);
DEFINE_SFR(__u0cr1_type, __u0cr1, 0x111);
DEFINE_SFR(__u0cr2_type, __u0cr2, 0x112);
DEFINE_SFR(__sfr_byte, __txr_rxr0, 0x113);
DEFINE_SFR(__sfr_byte, __brg0, 0x114);
DEFINE_SFR(__u1sr_type, __u1sr, 0x115);
DEFINE_SFR(__u1cr1_type, __u1cr1, 0x116);
DEFINE_SFR(__u1cr2_type, __u1cr2, 0x117);
DEFINE_SFR(__sfr_byte, __txr_rxr1, 0x118);
DEFINE_SFR(__sfr_byte, __brg1, 0x119);
DEFINE_SFR(__ptm1c0_type, __ptm1c0, 0x11a);
DEFINE_SFR(__ptm1c1_type, __ptm1c1, 0x11b);
DEFINE_SFR(__sfr_byte, __ptm1dl, 0x11c);
DEFINE_SFR(__sfr_byte, __ptm1dh, 0x11d);
DEFINE_SFR(__sfr_byte, __ptm1al, 0x11e);
DEFINE_SFR(__sfr_byte, __ptm1ah, 0x11f);
DEFINE_SFR(__ptm1rpl_type, __ptm1rpl, 0x120);
DEFINE_SFR(__ptm1rph_type, __ptm1rph, 0x121);
DEFINE_SFR(__ptm2c0_type, __ptm2c0, 0x122);
DEFINE_SFR(__ptm2c1_type, __ptm2c1, 0x123);
DEFINE_SFR(__sfr_byte, __ptm2dl, 0x124);
DEFINE_SFR(__sfr_byte, __ptm2dh, 0x125);
DEFINE_SFR(__sfr_byte, __ptm2al, 0x126);
DEFINE_SFR(__sfr_byte, __ptm2ah, 0x127);
DEFINE_SFR(__ptm2rpl_type, __ptm2rpl, 0x128);
DEFINE_SFR(__ptm2rph_type, __ptm2rph, 0x129);
DEFINE_SFR(__ptm3c0_type, __ptm3c0, 0x12a);
DEFINE_SFR(__ptm3c1_type, __ptm3c1, 0x12b);
DEFINE_SFR(__sfr_byte, __ptm3dl, 0x12c);
DEFINE_SFR(__sfr_byte, __ptm3dh, 0x12d);
DEFINE_SFR(__sfr_byte, __ptm3al, 0x12e);
DEFINE_SFR(__sfr_byte, __ptm3ah, 0x12f);
DEFINE_SFR(__ptm3rpl_type, __ptm3rpl, 0x130);
DEFINE_SFR(__ptm3rph_type, __ptm3rph, 0x131);
DEFINE_SFR(__stm1c0_type, __stm1c0, 0x132);
DEFINE_SFR(__stm1c1_type, __stm1c1, 0x133);
DEFINE_SFR(__sfr_byte, __stm1dl, 0x134);
DEFINE_SFR(__sfr_byte, __stm1dh, 0x135);
DEFINE_SFR(__sfr_byte, __stm1al, 0x136);
DEFINE_SFR(__sfr_byte, __stm1ah, 0x137);
DEFINE_SFR(__stm1rp_type, __stm1rp, 0x138);
DEFINE_SFR(__stm2c0_type, __stm2c0, 0x139);
DEFINE_SFR(__stm2c1_type, __stm2c1, 0x13a);
DEFINE_SFR(__sfr_byte, __stm2dl, 0x13b);
DEFINE_SFR(__sfr_byte, __stm2dh, 0x13c);
DEFINE_SFR(__sfr_byte, __stm2al, 0x13d);
DEFINE_SFR(__sfr_byte, __stm2ah, 0x13e);
DEFINE_SFR(__stm2rp_type, __stm2rp, 0x13f);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__fc0_type, __fc0, 0x143);
DEFINE_SFR(__sfr_byte, __fc1, 0x144);
DEFINE_SFR(__fc2_type, __fc2, 0x145);
DEFINE_SFR(__ifs0_type, __ifs0, 0x148);
DEFINE_SFR(__ifs1_type, __ifs1, 0x149);
DEFINE_SFR(__ifs2_type, __ifs2, 0x14a);
DEFINE_SFR(__ifs3_type, __ifs3, 0x14b);
DEFINE_SFR(__pas0_type, __pas0, 0x14d);
DEFINE_SFR(__pas1_type, __pas1, 0x14e);
DEFINE_SFR(__pbs0_type, __pbs0, 0x14f);
DEFINE_SFR(__pbs1_type, __pbs1, 0x150);
DEFINE_SFR(__pcs0_type, __pcs0, 0x151);
DEFINE_SFR(__pcs1_type, __pcs1, 0x152);
DEFINE_SFR(__pds0_type, __pds0, 0x153);
DEFINE_SFR(__pds1_type, __pds1, 0x154);
DEFINE_SFR(__pes0_type, __pes0, 0x155);
DEFINE_SFR(__pes1_type, __pes1, 0x156);
DEFINE_SFR(__pfs0_type, __pfs0, 0x157);
DEFINE_SFR(__pfs1_type, __pfs1, 0x158);
DEFINE_SFR(__pgs0_type, __pgs0, 0x159);
DEFINE_SFR(__pgs1_type, __pgs1, 0x15a);
DEFINE_SFR(__phs0_type, __phs0, 0x15b);
DEFINE_SFR(__phs1_type, __phs1, 0x15c);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);
DEFINE_SFR(__sfr_byte, __iar2, 0x0C);

#define _iar0     __iar0
#define _iar1     __iar1
#define _iar2     __iar2
#define _mp0      __mp0
#define _mp1l     __mp1l
#define _mp1h     __mp1h
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _tbhp     __tbhp
#define _status   __status.byte
#define _pbp      __pbp.byte
#define _mp2l     __mp2l
#define _mp2h     __mp2h
#define _rstfc    __rstfc.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _intc3    __intc3.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _papu     __papu.byte
#define _pawu     __pawu.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pbpu     __pbpu.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pcpu     __pcpu.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _pdpu     __pdpu.byte
#define _pe       __pe.byte
#define _pec      __pec.byte
#define _pepu     __pepu.byte
#define _pf       __pf.byte
#define _pfc      __pfc.byte
#define _pfpu     __pfpu.byte
#define _pg       __pg.byte
#define _pgc      __pgc.byte
#define _pgpu     __pgpu.byte
#define _ph       __ph.byte
#define _phc      __phc.byte
#define _phpu     __phpu.byte
#define _pmps     __pmps.byte
#define _rstc     __rstc.byte
#define _vbgrc    __vbgrc.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _mfi3     __mfi3.byte
#define _mfi4     __mfi4.byte
#define _mfi5     __mfi5.byte
#define _integ    __integ.byte
#define _scc      __scc.byte
#define _hircc    __hircc.byte
#define _hxtc     __hxtc.byte
#define _lxtc     __lxtc.byte
#define _wdtc     __wdtc.byte
#define _lvrc     __lvrc.byte
#define _lvdc     __lvdc.byte
#define _eeal     __eeal.byte
#define _eeah     __eeah.byte
#define _eed      __eed
#define _cp0c     __cp0c.byte
#define _cp1c     __cp1c.byte
#define _ptm0c0   __ptm0c0.byte
#define _ptm0c1   __ptm0c1.byte
#define _ptm0dl   __ptm0dl
#define _ptm0dh   __ptm0dh
#define _ptm0al   __ptm0al
#define _ptm0ah   __ptm0ah
#define _ptm0rpl  __ptm0rpl.byte
#define _ptm0rph  __ptm0rph.byte
#define _stm0c0   __stm0c0.byte
#define _stm0c1   __stm0c1.byte
#define _stm0dl   __stm0dl
#define _stm0dh   __stm0dh
#define _stm0al   __stm0al
#define _stm0ah   __stm0ah
#define _stm0rp   __stm0rp.byte
#define _sledc0   __sledc0.byte
#define _sledc1   __sledc1.byte
#define _sledc2   __sledc2.byte
#define _sledc3   __sledc3.byte
#define _mduwr0   __mduwr0
#define _mduwr1   __mduwr1
#define _mduwr2   __mduwr2
#define _mduwr3   __mduwr3
#define _mduwr4   __mduwr4
#define _mduwr5   __mduwr5
#define _mduwctrl __mduwctrl.byte
#define _cp0vos   __cp0vos.byte
#define _cp1vos   __cp1vos.byte
#define _psc0r    __psc0r.byte
#define _tb0c     __tb0c.byte
#define _tb1c     __tb1c.byte
#define _psc1r    __psc1r.byte
#define _sadol    __sadol
#define _sadoh    __sadoh
#define _sadc0    __sadc0.byte
#define _sadc1    __sadc1.byte
#define _sadc2    __sadc2.byte
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simd     __simd
#define _simc2    __simc2.byte
#define _sima     __sima.byte
#define _simtoc   __simtoc.byte
#define _spiac0   __spiac0.byte
#define _spiac1   __spiac1.byte
#define _spiad    __spiad
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _scomc    __scomc.byte
#define _crccr    __crccr.byte
#define _crcin    __crcin
#define _crcdl    __crcdl
#define _crcdh    __crcdh
#define _iecc     __iecc.byte
#define _u2sr     __u2sr.byte
#define _u2cr1    __u2cr1.byte
#define _u2cr2    __u2cr2.byte
#define _txr_rxr2 __txr_rxr2
#define _brg2     __brg2
#define _u0sr     __u0sr.byte
#define _u0cr1    __u0cr1.byte
#define _u0cr2    __u0cr2.byte
#define _txr_rxr0 __txr_rxr0
#define _brg0     __brg0
#define _u1sr     __u1sr.byte
#define _u1cr1    __u1cr1.byte
#define _u1cr2    __u1cr2.byte
#define _txr_rxr1 __txr_rxr1
#define _brg1     __brg1
#define _ptm1c0   __ptm1c0.byte
#define _ptm1c1   __ptm1c1.byte
#define _ptm1dl   __ptm1dl
#define _ptm1dh   __ptm1dh
#define _ptm1al   __ptm1al
#define _ptm1ah   __ptm1ah
#define _ptm1rpl  __ptm1rpl.byte
#define _ptm1rph  __ptm1rph.byte
#define _ptm2c0   __ptm2c0.byte
#define _ptm2c1   __ptm2c1.byte
#define _ptm2dl   __ptm2dl
#define _ptm2dh   __ptm2dh
#define _ptm2al   __ptm2al
#define _ptm2ah   __ptm2ah
#define _ptm2rpl  __ptm2rpl.byte
#define _ptm2rph  __ptm2rph.byte
#define _ptm3c0   __ptm3c0.byte
#define _ptm3c1   __ptm3c1.byte
#define _ptm3dl   __ptm3dl
#define _ptm3dh   __ptm3dh
#define _ptm3al   __ptm3al
#define _ptm3ah   __ptm3ah
#define _ptm3rpl  __ptm3rpl.byte
#define _ptm3rph  __ptm3rph.byte
#define _stm1c0   __stm1c0.byte
#define _stm1c1   __stm1c1.byte
#define _stm1dl   __stm1dl
#define _stm1dh   __stm1dh
#define _stm1al   __stm1al
#define _stm1ah   __stm1ah
#define _stm1rp   __stm1rp.byte
#define _stm2c0   __stm2c0.byte
#define _stm2c1   __stm2c1.byte
#define _stm2dl   __stm2dl
#define _stm2dh   __stm2dh
#define _stm2al   __stm2al
#define _stm2ah   __stm2ah
#define _stm2rp   __stm2rp.byte
#define _eec      __eec.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _fc2      __fc2.byte
#define _ifs0     __ifs0.byte
#define _ifs1     __ifs1.byte
#define _ifs2     __ifs2.byte
#define _ifs3     __ifs3.byte
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pbs0     __pbs0.byte
#define _pbs1     __pbs1.byte
#define _pcs0     __pcs0.byte
#define _pcs1     __pcs1.byte
#define _pds0     __pds0.byte
#define _pds1     __pds1.byte
#define _pes0     __pes0.byte
#define _pes1     __pes1.byte
#define _pfs0     __pfs0.byte
#define _pfs1     __pfs1.byte
#define _pgs0     __pgs0.byte
#define _pgs1     __pgs1.byte
#define _phs0     __phs0.byte
#define _phs1     __phs1.byte

#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _pbp0     __pbp.bits.__pbp0
#define _pbp1     __pbp.bits.__pbp1
#define _pbp2     __pbp.bits.__pbp2
#define _wrf      __rstfc.bits.__wrf
#define _lrf      __rstfc.bits.__lrf
#define _lvrf     __rstfc.bits.__lvrf
#define _rstf     __rstfc.bits.__rstf
#define _emi      __intc0.bits.__emi
#define _int0e    __intc0.bits.__int0e
#define _int1e    __intc0.bits.__int1e
#define _cp0e     __intc0.bits.__cp0e
#define _int0f    __intc0.bits.__int0f
#define _int1f    __intc0.bits.__int1f
#define _cp0f     __intc0.bits.__cp0f
#define _cp1e     __intc1.bits.__cp1e
#define _mf0e     __intc1.bits.__mf0e
#define _mf1e     __intc1.bits.__mf1e
#define _ade      __intc1.bits.__ade
#define _cp1f     __intc1.bits.__cp1f
#define _mf0f     __intc1.bits.__mf0f
#define _mf1f     __intc1.bits.__mf1f
#define _adf      __intc1.bits.__adf
#define _mf2e     __intc2.bits.__mf2e
#define _tb0e     __intc2.bits.__tb0e
#define _tb1e     __intc2.bits.__tb1e
#define _mf3e     __intc2.bits.__mf3e
#define _mf2f     __intc2.bits.__mf2f
#define _tb0f     __intc2.bits.__tb0f
#define _tb1f     __intc2.bits.__tb1f
#define _mf3f     __intc2.bits.__mf3f
#define _int2e    __intc3.bits.__int2e
#define _int3e    __intc3.bits.__int3e
#define _mf4e     __intc3.bits.__mf4e
#define _mf5e     __intc3.bits.__mf5e
#define _int2f    __intc3.bits.__int2f
#define _int3f    __intc3.bits.__int3f
#define _mf4f     __intc3.bits.__mf4f
#define _mf5f     __intc3.bits.__mf5f
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pb4      __pb.bits.__pb4
#define _pb5      __pb.bits.__pb5
#define _pb6      __pb.bits.__pb6
#define _pb7      __pb.bits.__pb7
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbc4     __pbc.bits.__pbc4
#define _pbc5     __pbc.bits.__pbc5
#define _pbc6     __pbc.bits.__pbc6
#define _pbc7     __pbc.bits.__pbc7
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pbpu4    __pbpu.bits.__pbpu4
#define _pbpu5    __pbpu.bits.__pbpu5
#define _pbpu6    __pbpu.bits.__pbpu6
#define _pbpu7    __pbpu.bits.__pbpu7
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pc6      __pc.bits.__pc6
#define _pc7      __pc.bits.__pc7
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcc6     __pcc.bits.__pcc6
#define _pcc7     __pcc.bits.__pcc7
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pcpu6    __pcpu.bits.__pcpu6
#define _pcpu7    __pcpu.bits.__pcpu7
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pd3      __pd.bits.__pd3
#define _pd4      __pd.bits.__pd4
#define _pd5      __pd.bits.__pd5
#define _pd6      __pd.bits.__pd6
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _pdc3     __pdc.bits.__pdc3
#define _pdc4     __pdc.bits.__pdc4
#define _pdc5     __pdc.bits.__pdc5
#define _pdc6     __pdc.bits.__pdc6
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pdpu3    __pdpu.bits.__pdpu3
#define _pdpu4    __pdpu.bits.__pdpu4
#define _pdpu5    __pdpu.bits.__pdpu5
#define _pdpu6    __pdpu.bits.__pdpu6
#define _pe0      __pe.bits.__pe0
#define _pe1      __pe.bits.__pe1
#define _pe2      __pe.bits.__pe2
#define _pe3      __pe.bits.__pe3
#define _pe4      __pe.bits.__pe4
#define _pec0     __pec.bits.__pec0
#define _pec1     __pec.bits.__pec1
#define _pec2     __pec.bits.__pec2
#define _pec3     __pec.bits.__pec3
#define _pec4     __pec.bits.__pec4
#define _pepu0    __pepu.bits.__pepu0
#define _pepu1    __pepu.bits.__pepu1
#define _pepu2    __pepu.bits.__pepu2
#define _pepu3    __pepu.bits.__pepu3
#define _pepu4    __pepu.bits.__pepu4
#define _pf0      __pf.bits.__pf0
#define _pf1      __pf.bits.__pf1
#define _pf2      __pf.bits.__pf2
#define _pf3      __pf.bits.__pf3
#define _pf4      __pf.bits.__pf4
#define _pf5      __pf.bits.__pf5
#define _pf6      __pf.bits.__pf6
#define _pf7      __pf.bits.__pf7
#define _pfc0     __pfc.bits.__pfc0
#define _pfc1     __pfc.bits.__pfc1
#define _pfc2     __pfc.bits.__pfc2
#define _pfc3     __pfc.bits.__pfc3
#define _pfc4     __pfc.bits.__pfc4
#define _pfc5     __pfc.bits.__pfc5
#define _pfc6     __pfc.bits.__pfc6
#define _pfc7     __pfc.bits.__pfc7
#define _pfpu0    __pfpu.bits.__pfpu0
#define _pfpu1    __pfpu.bits.__pfpu1
#define _pfpu2    __pfpu.bits.__pfpu2
#define _pfpu3    __pfpu.bits.__pfpu3
#define _pfpu4    __pfpu.bits.__pfpu4
#define _pfpu5    __pfpu.bits.__pfpu5
#define _pfpu6    __pfpu.bits.__pfpu6
#define _pfpu7    __pfpu.bits.__pfpu7
#define _pg0      __pg.bits.__pg0
#define _pg1      __pg.bits.__pg1
#define _pg2      __pg.bits.__pg2
#define _pg3      __pg.bits.__pg3
#define _pg4      __pg.bits.__pg4
#define _pg5      __pg.bits.__pg5
#define _pg6      __pg.bits.__pg6
#define _pg7      __pg.bits.__pg7
#define _pgc0     __pgc.bits.__pgc0
#define _pgc1     __pgc.bits.__pgc1
#define _pgc2     __pgc.bits.__pgc2
#define _pgc3     __pgc.bits.__pgc3
#define _pgc4     __pgc.bits.__pgc4
#define _pgc5     __pgc.bits.__pgc5
#define _pgc6     __pgc.bits.__pgc6
#define _pgc7     __pgc.bits.__pgc7
#define _pgpu0    __pgpu.bits.__pgpu0
#define _pgpu1    __pgpu.bits.__pgpu1
#define _pgpu2    __pgpu.bits.__pgpu2
#define _pgpu3    __pgpu.bits.__pgpu3
#define _pgpu4    __pgpu.bits.__pgpu4
#define _pgpu5    __pgpu.bits.__pgpu5
#define _pgpu6    __pgpu.bits.__pgpu6
#define _pgpu7    __pgpu.bits.__pgpu7
#define _ph0      __ph.bits.__ph0
#define _ph1      __ph.bits.__ph1
#define _ph2      __ph.bits.__ph2
#define _ph3      __ph.bits.__ph3
#define _ph4      __ph.bits.__ph4
#define _ph5      __ph.bits.__ph5
#define _phc0     __phc.bits.__phc0
#define _phc1     __phc.bits.__phc1
#define _phc2     __phc.bits.__phc2
#define _phc3     __phc.bits.__phc3
#define _phc4     __phc.bits.__phc4
#define _phc5     __phc.bits.__phc5
#define _phpu0    __phpu.bits.__phpu0
#define _phpu1    __phpu.bits.__phpu1
#define _phpu2    __phpu.bits.__phpu2
#define _phpu3    __phpu.bits.__phpu3
#define _phpu4    __phpu.bits.__phpu4
#define _phpu5    __phpu.bits.__phpu5
#define _pmps0    __pmps.bits.__pmps0
#define _pmps1    __pmps.bits.__pmps1
#define _rstc0    __rstc.bits.__rstc0
#define _rstc1    __rstc.bits.__rstc1
#define _rstc2    __rstc.bits.__rstc2
#define _rstc3    __rstc.bits.__rstc3
#define _rstc4    __rstc.bits.__rstc4
#define _rstc5    __rstc.bits.__rstc5
#define _rstc6    __rstc.bits.__rstc6
#define _rstc7    __rstc.bits.__rstc7
#define _vbgren   __vbgrc.bits.__vbgren
#define _ptm0pe   __mfi0.bits.__ptm0pe
#define _ptm0ae   __mfi0.bits.__ptm0ae
#define _stm0pe   __mfi0.bits.__stm0pe
#define _stm0ae   __mfi0.bits.__stm0ae
#define _ptm0pf   __mfi0.bits.__ptm0pf
#define _ptm0af   __mfi0.bits.__ptm0af
#define _stm0pf   __mfi0.bits.__stm0pf
#define _stm0af   __mfi0.bits.__stm0af
#define _ptm1pe   __mfi1.bits.__ptm1pe
#define _ptm1ae   __mfi1.bits.__ptm1ae
#define _stm1pe   __mfi1.bits.__stm1pe
#define _stm1ae   __mfi1.bits.__stm1ae
#define _ptm1pf   __mfi1.bits.__ptm1pf
#define _ptm1af   __mfi1.bits.__ptm1af
#define _stm1pf   __mfi1.bits.__stm1pf
#define _stm1af   __mfi1.bits.__stm1af
#define _ptm2pe   __mfi2.bits.__ptm2pe
#define _ptm2ae   __mfi2.bits.__ptm2ae
#define _ptm2pf   __mfi2.bits.__ptm2pf
#define _ptm2af   __mfi2.bits.__ptm2af
#define _lve      __mfi3.bits.__lve
#define _dee      __mfi3.bits.__dee
#define _spiae    __mfi3.bits.__spiae
#define _sime     __mfi3.bits.__sime
#define _lvf      __mfi3.bits.__lvf
#define _def      __mfi3.bits.__def
#define _spiaf    __mfi3.bits.__spiaf
#define _simf     __mfi3.bits.__simf
#define _ptm3pe   __mfi4.bits.__ptm3pe
#define _ptm3ae   __mfi4.bits.__ptm3ae
#define _stm2pe   __mfi4.bits.__stm2pe
#define _stm2ae   __mfi4.bits.__stm2ae
#define _ptm3pf   __mfi4.bits.__ptm3pf
#define _ptm3af   __mfi4.bits.__ptm3af
#define _stm2pf   __mfi4.bits.__stm2pf
#define _stm2af   __mfi4.bits.__stm2af
#define _ur0e     __mfi5.bits.__ur0e
#define _ur1e     __mfi5.bits.__ur1e
#define _ur2e     __mfi5.bits.__ur2e
#define _ur0f     __mfi5.bits.__ur0f
#define _ur1f     __mfi5.bits.__ur1f
#define _ur2f     __mfi5.bits.__ur2f
#define _int0s0   __integ.bits.__int0s0
#define _int0s1   __integ.bits.__int0s1
#define _int1s0   __integ.bits.__int1s0
#define _int1s1   __integ.bits.__int1s1
#define _int2s0   __integ.bits.__int2s0
#define _int2s1   __integ.bits.__int2s1
#define _int3s0   __integ.bits.__int3s0
#define _int3s1   __integ.bits.__int3s1
#define _fsiden   __scc.bits.__fsiden
#define _fhiden   __scc.bits.__fhiden
#define _fss      __scc.bits.__fss
#define _fhs      __scc.bits.__fhs
#define _cks0     __scc.bits.__cks0
#define _cks1     __scc.bits.__cks1
#define _cks2     __scc.bits.__cks2
#define _hircen   __hircc.bits.__hircen
#define _hircf    __hircc.bits.__hircf
#define _hirc0    __hircc.bits.__hirc0
#define _hirc1    __hircc.bits.__hirc1
#define _hxten    __hxtc.bits.__hxten
#define _hxtf     __hxtc.bits.__hxtf
#define _hxtm     __hxtc.bits.__hxtm
#define _lxten    __lxtc.bits.__lxten
#define _lxtf     __lxtc.bits.__lxtf
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _lvs0     __lvrc.bits.__lvs0
#define _lvs1     __lvrc.bits.__lvs1
#define _lvs2     __lvrc.bits.__lvs2
#define _lvs3     __lvrc.bits.__lvs3
#define _lvs4     __lvrc.bits.__lvs4
#define _lvs5     __lvrc.bits.__lvs5
#define _lvs6     __lvrc.bits.__lvs6
#define _lvs7     __lvrc.bits.__lvs7
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _vbgen    __lvdc.bits.__vbgen
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _eeal0    __eeal.bits.__eeal0
#define _eeal1    __eeal.bits.__eeal1
#define _eeal2    __eeal.bits.__eeal2
#define _eeal3    __eeal.bits.__eeal3
#define _eeal4    __eeal.bits.__eeal4
#define _eeal5    __eeal.bits.__eeal5
#define _eeal6    __eeal.bits.__eeal6
#define _eeal7    __eeal.bits.__eeal7
#define _eeah0    __eeah.bits.__eeah0
#define _eeah1    __eeah.bits.__eeah1
#define _cnvt00   __cp0c.bits.__cnvt00
#define _cnvt01   __cp0c.bits.__cnvt01
#define _c0out    __cp0c.bits.__c0out
#define _c0pol    __cp0c.bits.__c0pol
#define _c0en     __cp0c.bits.__c0en
#define _cnvt10   __cp1c.bits.__cnvt10
#define _cnvt11   __cp1c.bits.__cnvt11
#define _c1out    __cp1c.bits.__c1out
#define _c1pol    __cp1c.bits.__c1pol
#define _c1en     __cp1c.bits.__c1en
#define _pt0on    __ptm0c0.bits.__pt0on
#define _pt0ck0   __ptm0c0.bits.__pt0ck0
#define _pt0ck1   __ptm0c0.bits.__pt0ck1
#define _pt0ck2   __ptm0c0.bits.__pt0ck2
#define _pt0pau   __ptm0c0.bits.__pt0pau
#define _pt0cclr  __ptm0c1.bits.__pt0cclr
#define _pt0capts __ptm0c1.bits.__pt0capts
#define _pt0pol   __ptm0c1.bits.__pt0pol
#define _pt0oc    __ptm0c1.bits.__pt0oc
#define _pt0io0   __ptm0c1.bits.__pt0io0
#define _pt0io1   __ptm0c1.bits.__pt0io1
#define _pt0m0    __ptm0c1.bits.__pt0m0
#define _pt0m1    __ptm0c1.bits.__pt0m1
#define _pt0rp0   __ptm0rpl.bits.__pt0rp0
#define _pt0rp1   __ptm0rpl.bits.__pt0rp1
#define _pt0rp2   __ptm0rpl.bits.__pt0rp2
#define _pt0rp3   __ptm0rpl.bits.__pt0rp3
#define _pt0rp4   __ptm0rpl.bits.__pt0rp4
#define _pt0rp5   __ptm0rpl.bits.__pt0rp5
#define _pt0rp6   __ptm0rpl.bits.__pt0rp6
#define _pt0rp7   __ptm0rpl.bits.__pt0rp7
#define _pt0rp8   __ptm0rph.bits.__pt0rp8
#define _pt0rp9   __ptm0rph.bits.__pt0rp9
#define _st0on    __stm0c0.bits.__st0on
#define _st0ck0   __stm0c0.bits.__st0ck0
#define _st0ck1   __stm0c0.bits.__st0ck1
#define _st0ck2   __stm0c0.bits.__st0ck2
#define _st0pau   __stm0c0.bits.__st0pau
#define _st0cclr  __stm0c1.bits.__st0cclr
#define _st0dpx   __stm0c1.bits.__st0dpx
#define _st0pol   __stm0c1.bits.__st0pol
#define _st0oc    __stm0c1.bits.__st0oc
#define _st0io0   __stm0c1.bits.__st0io0
#define _st0io1   __stm0c1.bits.__st0io1
#define _st0m0    __stm0c1.bits.__st0m0
#define _st0m1    __stm0c1.bits.__st0m1
#define _st0rp0   __stm0rp.bits.__st0rp0
#define _st0rp1   __stm0rp.bits.__st0rp1
#define _st0rp2   __stm0rp.bits.__st0rp2
#define _st0rp3   __stm0rp.bits.__st0rp3
#define _st0rp4   __stm0rp.bits.__st0rp4
#define _st0rp5   __stm0rp.bits.__st0rp5
#define _st0rp6   __stm0rp.bits.__st0rp6
#define _st0rp7   __stm0rp.bits.__st0rp7
#define _sledc00  __sledc0.bits.__sledc00
#define _sledc01  __sledc0.bits.__sledc01
#define _sledc02  __sledc0.bits.__sledc02
#define _sledc03  __sledc0.bits.__sledc03
#define _sledc04  __sledc0.bits.__sledc04
#define _sledc05  __sledc0.bits.__sledc05
#define _sledc06  __sledc0.bits.__sledc06
#define _sledc07  __sledc0.bits.__sledc07
#define _sledc10  __sledc1.bits.__sledc10
#define _sledc11  __sledc1.bits.__sledc11
#define _sledc12  __sledc1.bits.__sledc12
#define _sledc13  __sledc1.bits.__sledc13
#define _sledc14  __sledc1.bits.__sledc14
#define _sledc15  __sledc1.bits.__sledc15
#define _sledc16  __sledc1.bits.__sledc16
#define _sledc17  __sledc1.bits.__sledc17
#define _sledc20  __sledc2.bits.__sledc20
#define _sledc21  __sledc2.bits.__sledc21
#define _sledc22  __sledc2.bits.__sledc22
#define _sledc23  __sledc2.bits.__sledc23
#define _sledc24  __sledc2.bits.__sledc24
#define _sledc25  __sledc2.bits.__sledc25
#define _sledc26  __sledc2.bits.__sledc26
#define _sledc27  __sledc2.bits.__sledc27
#define _sledc30  __sledc3.bits.__sledc30
#define _sledc31  __sledc3.bits.__sledc31
#define _sledc32  __sledc3.bits.__sledc32
#define _sledc33  __sledc3.bits.__sledc33
#define _sledc34  __sledc3.bits.__sledc34
#define _sledc35  __sledc3.bits.__sledc35
#define _sledc36  __sledc3.bits.__sledc36
#define _sledc37  __sledc3.bits.__sledc37
#define _mdwov    __mduwctrl.bits.__mdwov
#define _mdwef    __mduwctrl.bits.__mdwef
#define _c0of0    __cp0vos.bits.__c0of0
#define _c0of1    __cp0vos.bits.__c0of1
#define _c0of2    __cp0vos.bits.__c0of2
#define _c0of3    __cp0vos.bits.__c0of3
#define _c0of4    __cp0vos.bits.__c0of4
#define _c0rsp    __cp0vos.bits.__c0rsp
#define _c0ofm    __cp0vos.bits.__c0ofm
#define _c1of0    __cp1vos.bits.__c1of0
#define _c1of1    __cp1vos.bits.__c1of1
#define _c1of2    __cp1vos.bits.__c1of2
#define _c1of3    __cp1vos.bits.__c1of3
#define _c1of4    __cp1vos.bits.__c1of4
#define _c1rsp    __cp1vos.bits.__c1rsp
#define _c1ofm    __cp1vos.bits.__c1ofm
#define _clksel00 __psc0r.bits.__clksel00
#define _clksel01 __psc0r.bits.__clksel01
#define _tb00     __tb0c.bits.__tb00
#define _tb01     __tb0c.bits.__tb01
#define _tb02     __tb0c.bits.__tb02
#define _tb0on    __tb0c.bits.__tb0on
#define _tb10     __tb1c.bits.__tb10
#define _tb11     __tb1c.bits.__tb11
#define _tb12     __tb1c.bits.__tb12
#define _tb1on    __tb1c.bits.__tb1on
#define _clksel10 __psc1r.bits.__clksel10
#define _clksel11 __psc1r.bits.__clksel11
#define _sacs0    __sadc0.bits.__sacs0
#define _sacs1    __sadc0.bits.__sacs1
#define _sacs2    __sadc0.bits.__sacs2
#define _sacs3    __sadc0.bits.__sacs3
#define _adrfs    __sadc0.bits.__adrfs
#define _adcen    __sadc0.bits.__adcen
#define _adbz     __sadc0.bits.__adbz
#define _start    __sadc0.bits.__start
#define _sacks0   __sadc1.bits.__sacks0
#define _sacks1   __sadc1.bits.__sacks1
#define _sacks2   __sadc1.bits.__sacks2
#define _sains0   __sadc1.bits.__sains0
#define _sains1   __sadc1.bits.__sains1
#define _sains2   __sadc1.bits.__sains2
#define _sains3   __sadc1.bits.__sains3
#define _pgags0   __sadc2.bits.__pgags0
#define _pgags1   __sadc2.bits.__pgags1
#define _savrs0   __sadc2.bits.__savrs0
#define _savrs1   __sadc2.bits.__savrs1
#define _pgais    __sadc2.bits.__pgais
#define _adpgaen  __sadc2.bits.__adpgaen
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _iica0    __sima.bits.__iica0
#define _iica1    __sima.bits.__iica1
#define _iica2    __sima.bits.__iica2
#define _iica3    __sima.bits.__iica3
#define _iica4    __sima.bits.__iica4
#define _iica5    __sima.bits.__iica5
#define _iica6    __sima.bits.__iica6
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _spiaicf  __spiac0.bits.__spiaicf
#define _spiaen   __spiac0.bits.__spiaen
#define _saspi0   __spiac0.bits.__saspi0
#define _saspi1   __spiac0.bits.__saspi1
#define _saspi2   __spiac0.bits.__saspi2
#define _satrf    __spiac1.bits.__satrf
#define _sawcol   __spiac1.bits.__sawcol
#define _sacsen   __spiac1.bits.__sacsen
#define _samls    __spiac1.bits.__samls
#define _sackeg   __spiac1.bits.__sackeg
#define _sackpolb __spiac1.bits.__sackpolb
#define _a0       __farl.bits.__a0
#define _a1       __farl.bits.__a1
#define _a2       __farl.bits.__a2
#define _a3       __farl.bits.__a3
#define _a4       __farl.bits.__a4
#define _a5       __farl.bits.__a5
#define _a6       __farl.bits.__a6
#define _a7       __farl.bits.__a7
#define _a8       __farh.bits.__a8
#define _a9       __farh.bits.__a9
#define _a10      __farh.bits.__a10
#define _a11      __farh.bits.__a11
#define _a12      __farh.bits.__a12
#define _a13      __farh.bits.__a13
#define _a14      __farh.bits.__a14
#define _a15      __farh.bits.__a15
#define _scomen   __scomc.bits.__scomen
#define _isel0    __scomc.bits.__isel0
#define _isel1    __scomc.bits.__isel1
#define _poly     __crccr.bits.__poly
#define _iecs0    __iecc.bits.__iecs0
#define _iecs1    __iecc.bits.__iecs1
#define _iecs2    __iecc.bits.__iecs2
#define _iecs3    __iecc.bits.__iecs3
#define _iecs4    __iecc.bits.__iecs4
#define _iecs5    __iecc.bits.__iecs5
#define _iecs6    __iecc.bits.__iecs6
#define _iecs7    __iecc.bits.__iecs7
#define _txif2    __u2sr.bits.__txif2
#define _tidle2   __u2sr.bits.__tidle2
#define _rxif2    __u2sr.bits.__rxif2
#define _ridle2   __u2sr.bits.__ridle2
#define _oerr2    __u2sr.bits.__oerr2
#define _ferr2    __u2sr.bits.__ferr2
#define _nf2      __u2sr.bits.__nf2
#define _perr2    __u2sr.bits.__perr2
#define _tx82     __u2cr1.bits.__tx82
#define _rx82     __u2cr1.bits.__rx82
#define _txbrk2   __u2cr1.bits.__txbrk2
#define _stops2   __u2cr1.bits.__stops2
#define _prt2     __u2cr1.bits.__prt2
#define _pren2    __u2cr1.bits.__pren2
#define _bno2     __u2cr1.bits.__bno2
#define _uarten2  __u2cr1.bits.__uarten2
#define _teie2    __u2cr2.bits.__teie2
#define _tiie2    __u2cr2.bits.__tiie2
#define _rie2     __u2cr2.bits.__rie2
#define _wake2    __u2cr2.bits.__wake2
#define _adden2   __u2cr2.bits.__adden2
#define _brgh2    __u2cr2.bits.__brgh2
#define _rxen2    __u2cr2.bits.__rxen2
#define _txen2    __u2cr2.bits.__txen2
#define _txif0    __u0sr.bits.__txif0
#define _tidle0   __u0sr.bits.__tidle0
#define _rxif0    __u0sr.bits.__rxif0
#define _ridle0   __u0sr.bits.__ridle0
#define _oerr0    __u0sr.bits.__oerr0
#define _ferr0    __u0sr.bits.__ferr0
#define _nf0      __u0sr.bits.__nf0
#define _perr0    __u0sr.bits.__perr0
#define _tx80     __u0cr1.bits.__tx80
#define _rx80     __u0cr1.bits.__rx80
#define _txbrk0   __u0cr1.bits.__txbrk0
#define _stops0   __u0cr1.bits.__stops0
#define _prt0     __u0cr1.bits.__prt0
#define _pren0    __u0cr1.bits.__pren0
#define _bno0     __u0cr1.bits.__bno0
#define _uarten0  __u0cr1.bits.__uarten0
#define _teie0    __u0cr2.bits.__teie0
#define _tiie0    __u0cr2.bits.__tiie0
#define _rie0     __u0cr2.bits.__rie0
#define _wake0    __u0cr2.bits.__wake0
#define _adden0   __u0cr2.bits.__adden0
#define _brgh0    __u0cr2.bits.__brgh0
#define _rxen0    __u0cr2.bits.__rxen0
#define _txen0    __u0cr2.bits.__txen0
#define _txif1    __u1sr.bits.__txif1
#define _tidle1   __u1sr.bits.__tidle1
#define _rxif1    __u1sr.bits.__rxif1
#define _ridle1   __u1sr.bits.__ridle1
#define _oerr1    __u1sr.bits.__oerr1
#define _ferr1    __u1sr.bits.__ferr1
#define _nf1      __u1sr.bits.__nf1
#define _perr1    __u1sr.bits.__perr1
#define _tx81     __u1cr1.bits.__tx81
#define _rx81     __u1cr1.bits.__rx81
#define _txbrk1   __u1cr1.bits.__txbrk1
#define _stops1   __u1cr1.bits.__stops1
#define _prt1     __u1cr1.bits.__prt1
#define _pren1    __u1cr1.bits.__pren1
#define _bno1     __u1cr1.bits.__bno1
#define _uarten1  __u1cr1.bits.__uarten1
#define _teie1    __u1cr2.bits.__teie1
#define _tiie1    __u1cr2.bits.__tiie1
#define _rie1     __u1cr2.bits.__rie1
#define _wake1    __u1cr2.bits.__wake1
#define _adden1   __u1cr2.bits.__adden1
#define _brgh1    __u1cr2.bits.__brgh1
#define _rxen1    __u1cr2.bits.__rxen1
#define _txen1    __u1cr2.bits.__txen1
#define _pt1on    __ptm1c0.bits.__pt1on
#define _pt1ck0   __ptm1c0.bits.__pt1ck0
#define _pt1ck1   __ptm1c0.bits.__pt1ck1
#define _pt1ck2   __ptm1c0.bits.__pt1ck2
#define _pt1pau   __ptm1c0.bits.__pt1pau
#define _pt1cclr  __ptm1c1.bits.__pt1cclr
#define _pt1capts __ptm1c1.bits.__pt1capts
#define _pt1pol   __ptm1c1.bits.__pt1pol
#define _pt1oc    __ptm1c1.bits.__pt1oc
#define _pt1io0   __ptm1c1.bits.__pt1io0
#define _pt1io1   __ptm1c1.bits.__pt1io1
#define _pt1m0    __ptm1c1.bits.__pt1m0
#define _pt1m1    __ptm1c1.bits.__pt1m1
#define _pt1rp0   __ptm1rpl.bits.__pt1rp0
#define _pt1rp1   __ptm1rpl.bits.__pt1rp1
#define _pt1rp2   __ptm1rpl.bits.__pt1rp2
#define _pt1rp3   __ptm1rpl.bits.__pt1rp3
#define _pt1rp4   __ptm1rpl.bits.__pt1rp4
#define _pt1rp5   __ptm1rpl.bits.__pt1rp5
#define _pt1rp6   __ptm1rpl.bits.__pt1rp6
#define _pt1rp7   __ptm1rpl.bits.__pt1rp7
#define _pt1rp8   __ptm1rph.bits.__pt1rp8
#define _pt1rp9   __ptm1rph.bits.__pt1rp9
#define _pt2on    __ptm2c0.bits.__pt2on
#define _pt2ck0   __ptm2c0.bits.__pt2ck0
#define _pt2ck1   __ptm2c0.bits.__pt2ck1
#define _pt2ck2   __ptm2c0.bits.__pt2ck2
#define _pt2pau   __ptm2c0.bits.__pt2pau
#define _pt2cclr  __ptm2c1.bits.__pt2cclr
#define _pt2capts __ptm2c1.bits.__pt2capts
#define _pt2pol   __ptm2c1.bits.__pt2pol
#define _pt2oc    __ptm2c1.bits.__pt2oc
#define _pt2io0   __ptm2c1.bits.__pt2io0
#define _pt2io1   __ptm2c1.bits.__pt2io1
#define _pt2m0    __ptm2c1.bits.__pt2m0
#define _pt2m1    __ptm2c1.bits.__pt2m1
#define _pt2rp0   __ptm2rpl.bits.__pt2rp0
#define _pt2rp1   __ptm2rpl.bits.__pt2rp1
#define _pt2rp2   __ptm2rpl.bits.__pt2rp2
#define _pt2rp3   __ptm2rpl.bits.__pt2rp3
#define _pt2rp4   __ptm2rpl.bits.__pt2rp4
#define _pt2rp5   __ptm2rpl.bits.__pt2rp5
#define _pt2rp6   __ptm2rpl.bits.__pt2rp6
#define _pt2rp7   __ptm2rpl.bits.__pt2rp7
#define _pt2rp8   __ptm2rph.bits.__pt2rp8
#define _pt2rp9   __ptm2rph.bits.__pt2rp9
#define _pt2rp10  __ptm2rph.bits.__pt2rp10
#define _pt2rp11  __ptm2rph.bits.__pt2rp11
#define _pt2rp12  __ptm2rph.bits.__pt2rp12
#define _pt2rp13  __ptm2rph.bits.__pt2rp13
#define _pt2rp14  __ptm2rph.bits.__pt2rp14
#define _pt2rp15  __ptm2rph.bits.__pt2rp15
#define _pt3on    __ptm3c0.bits.__pt3on
#define _pt3ck0   __ptm3c0.bits.__pt3ck0
#define _pt3ck1   __ptm3c0.bits.__pt3ck1
#define _pt3ck2   __ptm3c0.bits.__pt3ck2
#define _pt3pau   __ptm3c0.bits.__pt3pau
#define _pt3cclr  __ptm3c1.bits.__pt3cclr
#define _pt3capts __ptm3c1.bits.__pt3capts
#define _pt3pol   __ptm3c1.bits.__pt3pol
#define _pt3oc    __ptm3c1.bits.__pt3oc
#define _pt3io0   __ptm3c1.bits.__pt3io0
#define _pt3io1   __ptm3c1.bits.__pt3io1
#define _pt3m0    __ptm3c1.bits.__pt3m0
#define _pt3m1    __ptm3c1.bits.__pt3m1
#define _pt3rp0   __ptm3rpl.bits.__pt3rp0
#define _pt3rp1   __ptm3rpl.bits.__pt3rp1
#define _pt3rp2   __ptm3rpl.bits.__pt3rp2
#define _pt3rp3   __ptm3rpl.bits.__pt3rp3
#define _pt3rp4   __ptm3rpl.bits.__pt3rp4
#define _pt3rp5   __ptm3rpl.bits.__pt3rp5
#define _pt3rp6   __ptm3rpl.bits.__pt3rp6
#define _pt3rp7   __ptm3rpl.bits.__pt3rp7
#define _pt3rp8   __ptm3rph.bits.__pt3rp8
#define _pt3rp9   __ptm3rph.bits.__pt3rp9
#define _pt3rp10  __ptm3rph.bits.__pt3rp10
#define _pt3rp11  __ptm3rph.bits.__pt3rp11
#define _pt3rp12  __ptm3rph.bits.__pt3rp12
#define _pt3rp13  __ptm3rph.bits.__pt3rp13
#define _pt3rp14  __ptm3rph.bits.__pt3rp14
#define _pt3rp15  __ptm3rph.bits.__pt3rp15
#define _st1on    __stm1c0.bits.__st1on
#define _st1ck0   __stm1c0.bits.__st1ck0
#define _st1ck1   __stm1c0.bits.__st1ck1
#define _st1ck2   __stm1c0.bits.__st1ck2
#define _st1pau   __stm1c0.bits.__st1pau
#define _st1cclr  __stm1c1.bits.__st1cclr
#define _st1dpx   __stm1c1.bits.__st1dpx
#define _st1pol   __stm1c1.bits.__st1pol
#define _st1oc    __stm1c1.bits.__st1oc
#define _st1io0   __stm1c1.bits.__st1io0
#define _st1io1   __stm1c1.bits.__st1io1
#define _st1m0    __stm1c1.bits.__st1m0
#define _st1m1    __stm1c1.bits.__st1m1
#define _st1rp0   __stm1rp.bits.__st1rp0
#define _st1rp1   __stm1rp.bits.__st1rp1
#define _st1rp2   __stm1rp.bits.__st1rp2
#define _st1rp3   __stm1rp.bits.__st1rp3
#define _st1rp4   __stm1rp.bits.__st1rp4
#define _st1rp5   __stm1rp.bits.__st1rp5
#define _st1rp6   __stm1rp.bits.__st1rp6
#define _st1rp7   __stm1rp.bits.__st1rp7
#define _st2on    __stm2c0.bits.__st2on
#define _st2ck0   __stm2c0.bits.__st2ck0
#define _st2ck1   __stm2c0.bits.__st2ck1
#define _st2ck2   __stm2c0.bits.__st2ck2
#define _st2pau   __stm2c0.bits.__st2pau
#define _st2cclr  __stm2c1.bits.__st2cclr
#define _st2dpx   __stm2c1.bits.__st2dpx
#define _st2pol   __stm2c1.bits.__st2pol
#define _st2oc    __stm2c1.bits.__st2oc
#define _st2io0   __stm2c1.bits.__st2io0
#define _st2io1   __stm2c1.bits.__st2io1
#define _st2m0    __stm2c1.bits.__st2m0
#define _st2m1    __stm2c1.bits.__st2m1
#define _st2rp0   __stm2rp.bits.__st2rp0
#define _st2rp1   __stm2rp.bits.__st2rp1
#define _st2rp2   __stm2rp.bits.__st2rp2
#define _st2rp3   __stm2rp.bits.__st2rp3
#define _st2rp4   __stm2rp.bits.__st2rp4
#define _st2rp5   __stm2rp.bits.__st2rp5
#define _st2rp6   __stm2rp.bits.__st2rp6
#define _st2rp7   __stm2rp.bits.__st2rp7
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _clwb     __fc2.bits.__clwb
#define _stck0ps  __ifs0.bits.__stck0ps
#define _stck1ps  __ifs0.bits.__stck1ps
#define _stck2ps  __ifs0.bits.__stck2ps
#define _ptck0ps  __ifs0.bits.__ptck0ps
#define _ptck1ps  __ifs0.bits.__ptck1ps
#define _ptck2ps  __ifs0.bits.__ptck2ps
#define _ptck3ps  __ifs0.bits.__ptck3ps
#define _stp0ips  __ifs1.bits.__stp0ips
#define _stp1ips  __ifs1.bits.__stp1ips
#define _stp2ips  __ifs1.bits.__stp2ips
#define _ptp0ips  __ifs1.bits.__ptp0ips
#define _ptp1ips  __ifs1.bits.__ptp1ips
#define _ptp2ips  __ifs1.bits.__ptp2ips
#define _ptp3ips  __ifs1.bits.__ptp3ips
#define _int0ps   __ifs2.bits.__int0ps
#define _int1ps   __ifs2.bits.__int1ps
#define _int2ps   __ifs2.bits.__int2ps
#define _int3ps   __ifs2.bits.__int3ps
#define _scksclps __ifs2.bits.__scksclps
#define _sdisdaps __ifs2.bits.__sdisdaps
#define _scsbps   __ifs2.bits.__scsbps
#define _rx0ps    __ifs3.bits.__rx0ps
#define _rx1ps    __ifs3.bits.__rx1ps
#define _rx2ps    __ifs3.bits.__rx2ps
#define _pas00    __pas0.bits.__pas00
#define _pas01    __pas0.bits.__pas01
#define _pas02    __pas0.bits.__pas02
#define _pas03    __pas0.bits.__pas03
#define _pas04    __pas0.bits.__pas04
#define _pas05    __pas0.bits.__pas05
#define _pas06    __pas0.bits.__pas06
#define _pas07    __pas0.bits.__pas07
#define _pas10    __pas1.bits.__pas10
#define _pas11    __pas1.bits.__pas11
#define _pas12    __pas1.bits.__pas12
#define _pas13    __pas1.bits.__pas13
#define _pas14    __pas1.bits.__pas14
#define _pas15    __pas1.bits.__pas15
#define _pas16    __pas1.bits.__pas16
#define _pas17    __pas1.bits.__pas17
#define _pbs00    __pbs0.bits.__pbs00
#define _pbs01    __pbs0.bits.__pbs01
#define _pbs02    __pbs0.bits.__pbs02
#define _pbs03    __pbs0.bits.__pbs03
#define _pbs04    __pbs0.bits.__pbs04
#define _pbs05    __pbs0.bits.__pbs05
#define _pbs06    __pbs0.bits.__pbs06
#define _pbs07    __pbs0.bits.__pbs07
#define _pbs10    __pbs1.bits.__pbs10
#define _pbs11    __pbs1.bits.__pbs11
#define _pbs12    __pbs1.bits.__pbs12
#define _pbs13    __pbs1.bits.__pbs13
#define _pbs14    __pbs1.bits.__pbs14
#define _pbs15    __pbs1.bits.__pbs15
#define _pbs16    __pbs1.bits.__pbs16
#define _pbs17    __pbs1.bits.__pbs17
#define _pcs00    __pcs0.bits.__pcs00
#define _pcs01    __pcs0.bits.__pcs01
#define _pcs02    __pcs0.bits.__pcs02
#define _pcs03    __pcs0.bits.__pcs03
#define _pcs04    __pcs0.bits.__pcs04
#define _pcs05    __pcs0.bits.__pcs05
#define _pcs06    __pcs0.bits.__pcs06
#define _pcs07    __pcs0.bits.__pcs07
#define _pcs10    __pcs1.bits.__pcs10
#define _pcs11    __pcs1.bits.__pcs11
#define _pcs12    __pcs1.bits.__pcs12
#define _pcs13    __pcs1.bits.__pcs13
#define _pcs14    __pcs1.bits.__pcs14
#define _pcs15    __pcs1.bits.__pcs15
#define _pcs16    __pcs1.bits.__pcs16
#define _pcs17    __pcs1.bits.__pcs17
#define _pds00    __pds0.bits.__pds00
#define _pds01    __pds0.bits.__pds01
#define _pds02    __pds0.bits.__pds02
#define _pds03    __pds0.bits.__pds03
#define _pds04    __pds0.bits.__pds04
#define _pds05    __pds0.bits.__pds05
#define _pds06    __pds0.bits.__pds06
#define _pds07    __pds0.bits.__pds07
#define _pds10    __pds1.bits.__pds10
#define _pds11    __pds1.bits.__pds11
#define _pds12    __pds1.bits.__pds12
#define _pds13    __pds1.bits.__pds13
#define _pds14    __pds1.bits.__pds14
#define _pds15    __pds1.bits.__pds15
#define _pes00    __pes0.bits.__pes00
#define _pes01    __pes0.bits.__pes01
#define _pes02    __pes0.bits.__pes02
#define _pes03    __pes0.bits.__pes03
#define _pes04    __pes0.bits.__pes04
#define _pes05    __pes0.bits.__pes05
#define _pes06    __pes0.bits.__pes06
#define _pes07    __pes0.bits.__pes07
#define _pes10    __pes1.bits.__pes10
#define _pes11    __pes1.bits.__pes11
#define _pfs00    __pfs0.bits.__pfs00
#define _pfs01    __pfs0.bits.__pfs01
#define _pfs02    __pfs0.bits.__pfs02
#define _pfs03    __pfs0.bits.__pfs03
#define _pfs04    __pfs0.bits.__pfs04
#define _pfs05    __pfs0.bits.__pfs05
#define _pfs06    __pfs0.bits.__pfs06
#define _pfs07    __pfs0.bits.__pfs07
#define _pfs10    __pfs1.bits.__pfs10
#define _pfs11    __pfs1.bits.__pfs11
#define _pfs12    __pfs1.bits.__pfs12
#define _pfs13    __pfs1.bits.__pfs13
#define _pfs14    __pfs1.bits.__pfs14
#define _pfs15    __pfs1.bits.__pfs15
#define _pfs16    __pfs1.bits.__pfs16
#define _pfs17    __pfs1.bits.__pfs17
#define _pgs00    __pgs0.bits.__pgs00
#define _pgs01    __pgs0.bits.__pgs01
#define _pgs02    __pgs0.bits.__pgs02
#define _pgs03    __pgs0.bits.__pgs03
#define _pgs04    __pgs0.bits.__pgs04
#define _pgs05    __pgs0.bits.__pgs05
#define _pgs06    __pgs0.bits.__pgs06
#define _pgs07    __pgs0.bits.__pgs07
#define _pgs10    __pgs1.bits.__pgs10
#define _pgs11    __pgs1.bits.__pgs11
#define _pgs12    __pgs1.bits.__pgs12
#define _pgs13    __pgs1.bits.__pgs13
#define _pgs14    __pgs1.bits.__pgs14
#define _pgs15    __pgs1.bits.__pgs15
#define _pgs16    __pgs1.bits.__pgs16
#define _pgs17    __pgs1.bits.__pgs17
#define _phs00    __phs0.bits.__phs00
#define _phs01    __phs0.bits.__phs01
#define _phs02    __phs0.bits.__phs02
#define _phs03    __phs0.bits.__phs03
#define _phs04    __phs0.bits.__phs04
#define _phs05    __phs0.bits.__phs05
#define _phs06    __phs0.bits.__phs06
#define _phs07    __phs0.bits.__phs07
#define _phs10    __phs1.bits.__phs10
#define _phs11    __phs1.bits.__phs11
#define _phs12    __phs1.bits.__phs12
#define _phs13    __phs1.bits.__phs13

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _HT66F2390_H_
